"""structure channel analysis reports

Revision ID: 0448c579cfab
Revises: 1c394b580ec5
Create Date: 2026-08-16 18:42:49.567759
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0448c579cfab'
down_revision: Union[str, None] = '1c394b580ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_analysis_evidence',
    sa.Column('report_id', sa.String(length=36), nullable=False, comment='分析报告ID'),
    sa.Column('source_type', sa.String(length=40), nullable=False, comment='证据业务实体类型'),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False, comment='证据业务实体稳定ID'),
    sa.Column('evidence_time', sa.DateTime(timezone=True), nullable=True, comment='证据对应业务时间'),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), server_default='0.5000', nullable=False, comment='证据权重，0到1'),
    sa.Column('summary', sa.Text(), nullable=True, comment='证据摘要'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("source_type IN ('channel_metric','video_metric','analytics_breakdown','youtube_video','comment','operation_package','schedule','channel_dna','manual')", name=op.f('ck_channel_analysis_evidence_valid_source_type')),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_channel_analysis_evidence_weight_range')),
    sa.ForeignKeyConstraint(['report_id'], ['channel_analysis_reports.id'], name=op.f('fk_channel_analysis_evidence_report_id_channel_analysis_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_analysis_evidence')),
    sa.UniqueConstraint('report_id', 'source_type', 'source_entity_id', name='uq_channel_analysis_evidence_source'),
    comment='频道分析报告使用的数据库证据关联'
    )
    op.create_index('ix_channel_analysis_evidence_report_type', 'channel_analysis_evidence', ['report_id', 'source_type'], unique=False)
    op.create_table('channel_analysis_keyword_scores',
    sa.Column('report_id', sa.String(length=36), nullable=False, comment='分析报告ID'),
    sa.Column('keyword', sa.String(length=255), nullable=False, comment='关键词正文'),
    sa.Column('language', sa.String(length=20), nullable=False, comment='关键词语言'),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=False, comment='关键词评分，0到1'),
    sa.Column('performance_level', sa.String(length=20), server_default='unknown', nullable=False, comment='高、中、低或未知表现'),
    sa.Column('rank_number', sa.Integer(), nullable=False, comment='报告内关键词排名'),
    sa.Column('evidence_summary', sa.Text(), nullable=True, comment='关键词评分证据摘要'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("performance_level IN ('high','medium','low','unknown')", name=op.f('ck_channel_analysis_keyword_scores_valid_performance_level')),
    sa.CheckConstraint('rank_number >= 1', name=op.f('ck_channel_analysis_keyword_scores_rank_positive')),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_channel_analysis_keyword_scores_score_range')),
    sa.ForeignKeyConstraint(['report_id'], ['channel_analysis_reports.id'], name=op.f('fk_channel_analysis_keyword_scores_report_id_channel_analysis_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_analysis_keyword_scores')),
    sa.UniqueConstraint('report_id', 'keyword', 'language', name='uq_channel_analysis_keyword_scores_keyword'),
    comment='频道分析报告中的关键词评分'
    )
    op.create_index('ix_channel_analysis_keyword_scores_report_rank', 'channel_analysis_keyword_scores', ['report_id', 'rank_number'], unique=False)
    op.create_table('channel_analysis_topic_scores',
    sa.Column('report_id', sa.String(length=36), nullable=False, comment='分析报告ID'),
    sa.Column('topic', sa.String(length=255), nullable=False, comment='题材或内容方向'),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=False, comment='题材评分，0到1'),
    sa.Column('trend', sa.String(length=20), server_default='unknown', nullable=False, comment='上升、稳定、下降或未知'),
    sa.Column('rank_number', sa.Integer(), nullable=False, comment='报告内题材排名'),
    sa.Column('evidence_summary', sa.Text(), nullable=True, comment='题材评分证据摘要'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("trend IN ('rising','stable','falling','unknown')", name=op.f('ck_channel_analysis_topic_scores_valid_trend')),
    sa.CheckConstraint('rank_number >= 1', name=op.f('ck_channel_analysis_topic_scores_rank_positive')),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_channel_analysis_topic_scores_score_range')),
    sa.ForeignKeyConstraint(['report_id'], ['channel_analysis_reports.id'], name=op.f('fk_channel_analysis_topic_scores_report_id_channel_analysis_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_analysis_topic_scores')),
    sa.UniqueConstraint('report_id', 'topic', name='uq_channel_analysis_topic_scores_topic'),
    comment='频道分析报告中的题材评分'
    )
    op.create_index('ix_channel_analysis_topic_scores_report_rank', 'channel_analysis_topic_scores', ['report_id', 'rank_number'], unique=False)
    op.create_table('channel_audience_profiles',
    sa.Column('report_id', sa.String(length=36), nullable=False, comment='分析报告ID'),
    sa.Column('profile_type', sa.String(length=30), nullable=False, comment='国家、设备、流量来源或行为等画像类型'),
    sa.Column('segment_value', sa.String(length=255), nullable=False, comment='画像分群值'),
    sa.Column('share', sa.Numeric(precision=8, scale=5), nullable=True, comment='该分群占比，0到1'),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=5), nullable=True, comment='该分群补充指标值'),
    sa.Column('rank_number', sa.Integer(), nullable=False, comment='同类画像排名'),
    sa.Column('summary', sa.Text(), nullable=True, comment='画像业务解释'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("profile_type IN ('country','device','traffic_source','active_time','age_group','gender','viewer_type','behavior','genre')", name=op.f('ck_channel_audience_profiles_valid_profile_type')),
    sa.CheckConstraint('rank_number >= 1', name=op.f('ck_channel_audience_profiles_rank_positive')),
    sa.CheckConstraint('share IS NULL OR (share >= 0 AND share <= 1)', name=op.f('ck_channel_audience_profiles_share_range')),
    sa.ForeignKeyConstraint(['report_id'], ['channel_analysis_reports.id'], name=op.f('fk_channel_audience_profiles_report_id_channel_analysis_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_audience_profiles')),
    sa.UniqueConstraint('report_id', 'profile_type', 'segment_value', name='uq_channel_audience_profiles_segment'),
    comment='频道分析报告中的结构化用户画像'
    )
    op.create_index('ix_channel_audience_profiles_report_type', 'channel_audience_profiles', ['report_id', 'profile_type', 'rank_number'], unique=False)
    op.create_table('channel_strategy_recommendations',
    sa.Column('report_id', sa.String(length=36), nullable=False, comment='分析报告ID'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='内容、排期、标题、封面等建议类别'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='建议优先级'),
    sa.Column('recommendation', sa.Text(), nullable=False, comment='可执行建议正文'),
    sa.Column('rationale', sa.Text(), nullable=True, comment='建议理由'),
    sa.Column('expected_impact', sa.Text(), nullable=True, comment='预期影响'),
    sa.Column('status', sa.String(length=20), server_default='proposed', nullable=False, comment='建议采用状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("category IN ('content','schedule','title','cover','description','community','playlist','risk')", name=op.f('ck_channel_strategy_recommendations_valid_category')),
    sa.CheckConstraint("status IN ('proposed','adopted','rejected','completed')", name=op.f('ck_channel_strategy_recommendations_valid_status')),
    sa.CheckConstraint('priority >= 1', name=op.f('ck_channel_strategy_recommendations_priority_positive')),
    sa.ForeignKeyConstraint(['report_id'], ['channel_analysis_reports.id'], name=op.f('fk_channel_strategy_recommendations_report_id_channel_analysis_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_strategy_recommendations')),
    sa.UniqueConstraint('report_id', 'category', 'priority', name='uq_channel_strategy_recommendations_priority'),
    comment='频道分析报告中的结构化策略建议'
    )
    op.create_index('ix_channel_strategy_recommendations_report_status', 'channel_strategy_recommendations', ['report_id', 'status', 'priority'], unique=False)
    op.add_column('channel_analysis_reports', sa.Column('version_number', sa.Integer(), nullable=False, comment='频道内分析报告版本号'))
    op.create_unique_constraint('uq_channel_analysis_reports_version', 'channel_analysis_reports', ['channel_id', 'version_number'])
    op.create_check_constraint(op.f('ck_channel_analysis_reports_version_positive'), 'channel_analysis_reports', 'version_number >= 1')
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_channel_analysis_reports_version_positive'), 'channel_analysis_reports', type_='check')
    op.drop_constraint('uq_channel_analysis_reports_version', 'channel_analysis_reports', type_='unique')
    op.drop_column('channel_analysis_reports', 'version_number')
    op.drop_index('ix_channel_strategy_recommendations_report_status', table_name='channel_strategy_recommendations')
    op.drop_table('channel_strategy_recommendations')
    op.drop_index('ix_channel_audience_profiles_report_type', table_name='channel_audience_profiles')
    op.drop_table('channel_audience_profiles')
    op.drop_index('ix_channel_analysis_topic_scores_report_rank', table_name='channel_analysis_topic_scores')
    op.drop_table('channel_analysis_topic_scores')
    op.drop_index('ix_channel_analysis_keyword_scores_report_rank', table_name='channel_analysis_keyword_scores')
    op.drop_table('channel_analysis_keyword_scores')
    op.drop_index('ix_channel_analysis_evidence_report_type', table_name='channel_analysis_evidence')
    op.drop_table('channel_analysis_evidence')
    # ### end Alembic commands ###
