"""add versioned skill registry

Revision ID: 107204d31ece
Revises: b5f39ba72e31
Create Date: 2026-08-16 23:52:07.908176
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '107204d31ece'
down_revision: Union[str, None] = 'b5f39ba72e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('code', sa.String(length=80), nullable=False, comment='系统内稳定Skill代码'),
    sa.Column('name', sa.String(length=160), nullable=False, comment='Skill显示名称'),
    sa.Column('purpose', sa.Text(), nullable=False, comment='Skill业务用途'),
    sa.Column('category', sa.String(length=60), nullable=False, comment='Skill能力分类'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='Skill生命周期状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','disabled','deprecated')", name=op.f('ck_skills_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('code', name=op.f('uq_skills_code')),
    comment='生产能力Skill稳定定义'
    )
    op.create_index('ix_skills_category_status', 'skills', ['category', 'status'], unique=False)
    op.create_table('skill_versions',
    sa.Column('skill_id', sa.String(length=36), nullable=False, comment='Skill稳定ID'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Skill内部递增版本号'),
    sa.Column('body_zh_cn', sa.Text(), nullable=False, comment='供业务审核和编辑的中文正文'),
    sa.Column('body_original', sa.Text(), nullable=False, comment='供正式执行的原文正文'),
    sa.Column('content_sha256', sa.String(length=64), nullable=False, comment='双语正文内容SHA256'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='Skill版本状态'),
    sa.Column('is_current', sa.Boolean(), nullable=True, comment='当前发布版本唯一标记，历史版本为空'),
    sa.Column('change_summary', sa.Text(), nullable=True, comment='版本修改说明'),
    sa.Column('created_by', sa.String(length=120), nullable=True, comment='版本创建操作者标识'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='版本发布时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("is_current IS NULL OR (is_current = 1 AND status = 'published')", name=op.f('ck_skill_versions_current_version_must_be_published')),
    sa.CheckConstraint("status IN ('draft','published','superseded','archived')", name=op.f('ck_skill_versions_valid_status')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_skill_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_versions_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_versions')),
    sa.UniqueConstraint('skill_id', 'content_sha256', name='uq_skill_versions_content'),
    sa.UniqueConstraint('skill_id', 'is_current', name='uq_skill_versions_current'),
    sa.UniqueConstraint('skill_id', 'version_number', name='uq_skill_versions_number'),
    comment='Skill双语正文不可变版本'
    )
    op.create_index('ix_skill_versions_skill_status', 'skill_versions', ['skill_id', 'status'], unique=False)
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name IN ('skills', 'skill_versions')
          AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE()
          AND table_name IN ('skills', 'skill_versions')
          AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text(
        "DELETE FROM schema_comments "
        "WHERE table_name IN ('skills', 'skill_versions')"
    ))
    op.drop_index('ix_skill_versions_skill_status', table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index('ix_skills_category_status', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
