"""enforce youtube metric ranges

Revision ID: 1c394b580ec5
Revises: 35af48c5c7d4
Create Date: 2026-08-16 18:33:33.476752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c394b580ec5'
down_revision: Union[str, None] = '35af48c5c7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_api_request_logs_quota_nonnegative'), 'api_request_logs', 'quota_units >= 0')
    op.create_check_constraint(op.f('ck_quota_usage_logs_units_nonnegative'), 'quota_usage_logs', 'units >= 0')
    op.create_check_constraint(op.f('ck_youtube_analytics_breakdowns_ctr_range'), 'youtube_analytics_breakdowns', 'ctr IS NULL OR (ctr >= 0 AND ctr <= 1)')
    op.create_check_constraint(op.f('ck_youtube_analytics_breakdowns_metrics_nonnegative'), 'youtube_analytics_breakdowns', 'views >= 0 AND watch_time_minutes >= 0 AND impressions >= 0')
    op.create_check_constraint(op.f('ck_youtube_analytics_breakdowns_valid_scope_reference'), 'youtube_analytics_breakdowns', "(scope_type = 'channel' AND video_id IS NULL) OR (scope_type = 'video' AND video_id IS NOT NULL)")
    op.create_check_constraint(op.f('ck_youtube_channel_daily_metrics_ctr_range'), 'youtube_channel_daily_metrics', 'ctr IS NULL OR (ctr >= 0 AND ctr <= 1)')
    op.create_check_constraint(op.f('ck_youtube_channel_daily_metrics_metrics_nonnegative'), 'youtube_channel_daily_metrics', 'views >= 0 AND watch_time_minutes >= 0 AND subscribers_gained >= 0 AND subscribers_lost >= 0 AND impressions >= 0')
    op.create_check_constraint(op.f('ck_youtube_comments_like_count_nonnegative'), 'youtube_comments', 'like_count >= 0')
    op.create_check_constraint(op.f('ck_youtube_video_daily_metrics_ctr_range'), 'youtube_video_daily_metrics', 'ctr IS NULL OR (ctr >= 0 AND ctr <= 1)')
    op.create_check_constraint(op.f('ck_youtube_video_daily_metrics_duration_nonnegative'), 'youtube_video_daily_metrics', 'average_view_duration_seconds IS NULL OR average_view_duration_seconds >= 0')
    op.create_check_constraint(op.f('ck_youtube_video_daily_metrics_metrics_nonnegative'), 'youtube_video_daily_metrics', 'views >= 0 AND impressions >= 0 AND watch_time_minutes >= 0 AND likes >= 0 AND comments >= 0 AND subscribers_gained >= 0')
    op.create_check_constraint(op.f('ck_youtube_video_playlist_memberships_position_nonnegative'), 'youtube_video_playlist_memberships', 'position_number IS NULL OR position_number >= 0')
    op.create_check_constraint(op.f('ck_youtube_videos_duration_nonnegative'), 'youtube_videos', 'duration_seconds IS NULL OR duration_seconds >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_youtube_videos_duration_nonnegative'), 'youtube_videos', type_='check')
    op.drop_constraint(op.f('ck_youtube_video_playlist_memberships_position_nonnegative'), 'youtube_video_playlist_memberships', type_='check')
    op.drop_constraint(op.f('ck_youtube_video_daily_metrics_metrics_nonnegative'), 'youtube_video_daily_metrics', type_='check')
    op.drop_constraint(op.f('ck_youtube_video_daily_metrics_duration_nonnegative'), 'youtube_video_daily_metrics', type_='check')
    op.drop_constraint(op.f('ck_youtube_video_daily_metrics_ctr_range'), 'youtube_video_daily_metrics', type_='check')
    op.drop_constraint(op.f('ck_youtube_comments_like_count_nonnegative'), 'youtube_comments', type_='check')
    op.drop_constraint(op.f('ck_youtube_channel_daily_metrics_metrics_nonnegative'), 'youtube_channel_daily_metrics', type_='check')
    op.drop_constraint(op.f('ck_youtube_channel_daily_metrics_ctr_range'), 'youtube_channel_daily_metrics', type_='check')
    op.drop_constraint(op.f('ck_youtube_analytics_breakdowns_valid_scope_reference'), 'youtube_analytics_breakdowns', type_='check')
    op.drop_constraint(op.f('ck_youtube_analytics_breakdowns_metrics_nonnegative'), 'youtube_analytics_breakdowns', type_='check')
    op.drop_constraint(op.f('ck_youtube_analytics_breakdowns_ctr_range'), 'youtube_analytics_breakdowns', type_='check')
    op.drop_constraint(op.f('ck_quota_usage_logs_units_nonnegative'), 'quota_usage_logs', type_='check')
    op.drop_constraint(op.f('ck_api_request_logs_quota_nonnegative'), 'api_request_logs', type_='check')
    # ### end Alembic commands ###

