"""add youtube publishing and analytics registry

Revision ID: 35af48c5c7d4
Revises: 9314c6bee5fb
Create Date: 2026-08-16 18:31:59.628351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35af48c5c7d4'
down_revision: Union[str, None] = '9314c6bee5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_watermarks',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('data_type', sa.String(length=60), nullable=False, comment='视频、评论、频道指标等同步类型'),
    sa.Column('status', sa.String(length=20), server_default='idle', nullable=False, comment='同步状态'),
    sa.Column('cursor_value', sa.String(length=1000), nullable=True, comment='第三方分页或增量游标'),
    sa.Column('data_through_at', sa.DateTime(timezone=True), nullable=True, comment='数据已同步至该时间'),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True, comment='最近开始时间'),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True, comment='最近成功时间'),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True, comment='最近失败时间'),
    sa.Column('error_code', sa.String(length=120), nullable=True, comment='最近失败代码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='最近失败脱敏信息'),
    sa.Column('lease_owner', sa.String(length=120), nullable=True, comment='当前同步工作器'),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True, comment='同步租约到期时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('idle','running','completed','failed')", name=op.f('ck_sync_watermarks_valid_status')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_sync_watermarks_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_watermarks')),
    sa.UniqueConstraint('channel_id', 'data_type', name='uq_sync_watermarks_channel_data_type'),
    comment='按频道和数据类型隔离的YouTube同步水位'
    )
    op.create_index('ix_sync_watermarks_status_lease', 'sync_watermarks', ['status', 'lease_expires_at'], unique=False)
    op.create_table('youtube_channel_daily_metrics',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('metric_date', sa.Date(), nullable=False, comment='指标所属日期'),
    sa.Column('views', sa.BigInteger(), server_default='0', nullable=False, comment='观看次数'),
    sa.Column('watch_time_minutes', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False, comment='观看时长分钟'),
    sa.Column('subscribers_gained', sa.BigInteger(), server_default='0', nullable=False, comment='新增订阅数'),
    sa.Column('subscribers_lost', sa.BigInteger(), server_default='0', nullable=False, comment='流失订阅数'),
    sa.Column('impressions', sa.BigInteger(), server_default='0', nullable=False, comment='展示次数'),
    sa.Column('ctr', sa.Numeric(precision=8, scale=5), nullable=True, comment='展示点击率'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False, comment='本快照同步时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_youtube_channel_daily_metrics_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_channel_daily_metrics')),
    sa.UniqueConstraint('channel_id', 'metric_date', name='uq_youtube_channel_daily_metrics_day'),
    comment='YouTube频道每日Analytics历史快照'
    )
    op.create_index('ix_youtube_channel_daily_metrics_date', 'youtube_channel_daily_metrics', ['metric_date', 'channel_id'], unique=False)
    op.create_table('api_request_logs',
    sa.Column('channel_id', sa.String(length=36), nullable=True, comment='关联频道内部ID'),
    sa.Column('authorization_id', sa.String(length=36), nullable=True, comment='使用的频道授权关系ID'),
    sa.Column('data_type', sa.String(length=60), nullable=False, comment='请求对应的数据类型'),
    sa.Column('endpoint', sa.String(length=255), nullable=False, comment='YouTube API端点'),
    sa.Column('http_method', sa.String(length=10), nullable=False, comment='HTTP方法'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='HTTP状态码'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='请求结果'),
    sa.Column('quota_units', sa.Integer(), server_default='0', nullable=False, comment='本次消耗配额单位'),
    sa.Column('response_item_count', sa.Integer(), nullable=True, comment='成功解析的业务条目数'),
    sa.Column('error_code', sa.String(length=120), nullable=True, comment='失败代码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败脱敏信息'),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False, comment='请求开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='请求结束时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.CheckConstraint("result IN ('success','failure','cancelled')", name=op.f('ck_api_request_logs_valid_result')),
    sa.ForeignKeyConstraint(['authorization_id'], ['account_channel_authorizations.id'], name=op.f('fk_api_request_logs_authorization_id_account_channel_authorizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_api_request_logs_channel_id_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_request_logs')),
    comment='YouTube API请求与结果日志'
    )
    op.create_index('ix_api_request_logs_channel_time', 'api_request_logs', ['channel_id', 'requested_at'], unique=False)
    op.create_index('ix_api_request_logs_data_type_time', 'api_request_logs', ['data_type', 'requested_at'], unique=False)
    op.create_table('quota_usage_logs',
    sa.Column('api_request_log_id', sa.String(length=36), nullable=False, comment='API请求日志ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=True, comment='关联频道内部ID'),
    sa.Column('account_id', sa.String(length=36), nullable=True, comment='配额所属Google账号ID'),
    sa.Column('quota_date', sa.Date(), nullable=False, comment='YouTube配额统计日期'),
    sa.Column('endpoint', sa.String(length=255), nullable=False, comment='消耗配额的API端点'),
    sa.Column('units', sa.Integer(), nullable=False, comment='消耗配额单位'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='记录时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.ForeignKeyConstraint(['account_id'], ['google_accounts.id'], name=op.f('fk_quota_usage_logs_account_id_google_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['api_request_log_id'], ['api_request_logs.id'], name=op.f('fk_quota_usage_logs_api_request_log_id_api_request_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_quota_usage_logs_channel_id_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quota_usage_logs')),
    sa.UniqueConstraint('api_request_log_id', name='uq_quota_usage_logs_request'),
    comment='YouTube API配额消耗明细'
    )
    op.create_index('ix_quota_usage_logs_date_channel', 'quota_usage_logs', ['quota_date', 'channel_id'], unique=False)
    op.create_table('youtube_videos',
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False, comment='YouTube视频外部ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='所属频道内部ID'),
    sa.Column('operation_package_id', sa.String(length=36), nullable=True, comment='来源运营包ID'),
    sa.Column('drama_id', sa.String(length=36), nullable=True, comment='关联剧目内部ID'),
    sa.Column('schedule_id', sa.String(length=36), nullable=True, comment='关联排期ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='YouTube当前标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='YouTube当前说明'),
    sa.Column('url', sa.String(length=1000), nullable=False, comment='YouTube视频地址'),
    sa.Column('privacy_status', sa.String(length=20), nullable=False, comment='公开视频、私享或不公开'),
    sa.Column('publish_status', sa.String(length=20), nullable=False, comment='草稿、预约、已发布、删除或异常'),
    sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False, comment='是否被运营标记为禁播'),
    sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True, comment='YouTube预约发布时间'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='实际发布时间'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='视频时长秒数'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='人工登记或YouTube同步'),
    sa.Column('etag', sa.String(length=255), nullable=True, comment='YouTube资源ETag'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='最后同步时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='确认从YouTube删除的时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("privacy_status IN ('public','private','unlisted')", name=op.f('ck_youtube_videos_valid_privacy_status')),
    sa.CheckConstraint("publish_status IN ('draft','scheduled','published','deleted','error')", name=op.f('ck_youtube_videos_valid_publish_status')),
    sa.CheckConstraint("source IN ('manual','youtube_sync')", name=op.f('ck_youtube_videos_valid_source')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_youtube_videos_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_youtube_videos_drama_id_dramas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_package_id'], ['operation_packages.id'], name=op.f('fk_youtube_videos_operation_package_id_operation_packages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['channel_schedule_entries.id'], name=op.f('fk_youtube_videos_schedule_id_channel_schedule_entries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_videos')),
    sa.UniqueConstraint('youtube_video_id', name=op.f('uq_youtube_videos_youtube_video_id')),
    comment='YouTube视频登记及当前发布状态'
    )
    op.create_index('ix_youtube_videos_channel_status', 'youtube_videos', ['channel_id', 'publish_status', 'privacy_status'], unique=False)
    op.create_index('ix_youtube_videos_package', 'youtube_videos', ['operation_package_id'], unique=False)
    op.create_table('youtube_analytics_breakdowns',
    sa.Column('scope_type', sa.String(length=20), nullable=False, comment='频道级或视频级'),
    sa.Column('scope_entity_id', sa.String(length=36), nullable=False, comment='频道ID或视频ID组成的非空作用域键'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('video_id', sa.String(length=36), nullable=True, comment='视频内部ID，频道级为空'),
    sa.Column('metric_date', sa.Date(), nullable=False, comment='指标所属日期'),
    sa.Column('dimension_type', sa.String(length=30), nullable=False, comment='国家、设备或流量来源等维度'),
    sa.Column('dimension_value', sa.String(length=255), nullable=False, comment='维度值'),
    sa.Column('views', sa.BigInteger(), server_default='0', nullable=False, comment='该维度观看次数'),
    sa.Column('watch_time_minutes', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False, comment='该维度观看时长分钟'),
    sa.Column('impressions', sa.BigInteger(), server_default='0', nullable=False, comment='该维度展示次数'),
    sa.Column('ctr', sa.Numeric(precision=8, scale=5), nullable=True, comment='该维度展示点击率'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False, comment='本指标同步时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("dimension_type IN ('country','device','traffic_source','age_group','gender','viewer_type')", name=op.f('ck_youtube_analytics_breakdowns_valid_dimension_type')),
    sa.CheckConstraint("scope_type IN ('channel','video')", name=op.f('ck_youtube_analytics_breakdowns_valid_scope_type')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_youtube_analytics_breakdowns_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], name=op.f('fk_youtube_analytics_breakdowns_video_id_youtube_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_analytics_breakdowns')),
    sa.UniqueConstraint('scope_type', 'scope_entity_id', 'metric_date', 'dimension_type', 'dimension_value', name='uq_youtube_analytics_breakdowns_identity'),
    comment='YouTube国家、设备、流量来源等维度指标'
    )
    op.create_index('ix_youtube_analytics_breakdowns_channel_date', 'youtube_analytics_breakdowns', ['channel_id', 'metric_date', 'dimension_type'], unique=False)
    op.create_table('youtube_comments',
    sa.Column('youtube_comment_id', sa.String(length=120), nullable=False, comment='YouTube评论外部ID'),
    sa.Column('video_id', sa.String(length=36), nullable=False, comment='所属视频内部ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='所属频道内部ID'),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True, comment='父评论内部ID'),
    sa.Column('author_channel_id', sa.String(length=100), nullable=True, comment='评论人YouTube频道ID'),
    sa.Column('author_display_name', sa.String(length=255), nullable=False, comment='评论人显示昵称'),
    sa.Column('original_text', sa.Text(), nullable=False, comment='原评论正文'),
    sa.Column('translated_text', sa.Text(), nullable=True, comment='评论中文翻译'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False, comment='评论发布时间'),
    sa.Column('youtube_updated_at', sa.DateTime(timezone=True), nullable=True, comment='YouTube评论更新时间'),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False, comment='评论点赞数'),
    sa.Column('is_channel_owner', sa.Boolean(), server_default='0', nullable=False, comment='是否频道自身评论'),
    sa.Column('reply_status', sa.String(length=20), server_default='unreplied', nullable=False, comment='回复处理状态'),
    sa.Column('moderation_status', sa.String(length=20), server_default='published', nullable=False, comment='YouTube审核状态'),
    sa.Column('sentiment', sa.String(length=40), nullable=True, comment='正向、负向、中性等情绪'),
    sa.Column('analysis_label', sa.String(length=80), nullable=True, comment='质疑、敏感、剧情讨论等分析标签'),
    sa.Column('recommended_reply', sa.Text(), nullable=True, comment='频道语言推荐回复'),
    sa.Column('recommended_reply_translation', sa.Text(), nullable=True, comment='推荐回复中文翻译'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False, comment='最后同步时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("moderation_status IN ('published','held','likely_spam','rejected','deleted')", name=op.f('ck_youtube_comments_valid_moderation_status')),
    sa.CheckConstraint("reply_status IN ('unreplied','suggested','replied','ignored','failed')", name=op.f('ck_youtube_comments_valid_reply_status')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_youtube_comments_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['youtube_comments.id'], name=op.f('fk_youtube_comments_parent_comment_id_youtube_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], name=op.f('fk_youtube_comments_video_id_youtube_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_comments')),
    sa.UniqueConstraint('youtube_comment_id', name=op.f('uq_youtube_comments_youtube_comment_id')),
    comment='YouTube评论及运营分析字段'
    )
    op.create_index('ix_youtube_comments_channel_reply', 'youtube_comments', ['channel_id', 'reply_status', 'published_at'], unique=False)
    op.create_index('ix_youtube_comments_video_time', 'youtube_comments', ['video_id', 'published_at'], unique=False)
    op.create_table('youtube_video_daily_metrics',
    sa.Column('video_id', sa.String(length=36), nullable=False, comment='视频内部ID'),
    sa.Column('metric_date', sa.Date(), nullable=False, comment='指标所属日期'),
    sa.Column('views', sa.BigInteger(), server_default='0', nullable=False, comment='观看次数'),
    sa.Column('impressions', sa.BigInteger(), server_default='0', nullable=False, comment='展示次数'),
    sa.Column('ctr', sa.Numeric(precision=8, scale=5), nullable=True, comment='展示点击率'),
    sa.Column('watch_time_minutes', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False, comment='观看时长分钟'),
    sa.Column('average_view_duration_seconds', sa.Numeric(precision=12, scale=3), nullable=True, comment='平均观看时长秒数'),
    sa.Column('likes', sa.BigInteger(), server_default='0', nullable=False, comment='点赞数'),
    sa.Column('comments', sa.BigInteger(), server_default='0', nullable=False, comment='评论数'),
    sa.Column('subscribers_gained', sa.BigInteger(), server_default='0', nullable=False, comment='带来的新增订阅数'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False, comment='本快照同步时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], name=op.f('fk_youtube_video_daily_metrics_video_id_youtube_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_video_daily_metrics')),
    sa.UniqueConstraint('video_id', 'metric_date', name='uq_youtube_video_daily_metrics_day'),
    comment='YouTube视频每日Analytics历史快照'
    )
    op.create_index('ix_youtube_video_daily_metrics_date', 'youtube_video_daily_metrics', ['metric_date', 'video_id'], unique=False)
    op.create_table('youtube_video_playlist_memberships',
    sa.Column('video_id', sa.String(length=36), nullable=False, comment='视频内部ID'),
    sa.Column('playlist_id', sa.String(length=36), nullable=False, comment='播放列表内部ID'),
    sa.Column('youtube_playlist_item_id', sa.String(length=100), nullable=True, comment='YouTube播放列表条目外部ID'),
    sa.Column('position_number', sa.Integer(), nullable=True, comment='YouTube播放列表内位置'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='当前归属状态'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='最后同步时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','removed')", name=op.f('ck_youtube_video_playlist_memberships_valid_status')),
    sa.ForeignKeyConstraint(['playlist_id'], ['channel_playlists.id'], name=op.f('fk_youtube_video_playlist_memberships_playlist_id_channel_playlists'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], name=op.f('fk_youtube_video_playlist_memberships_video_id_youtube_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_video_playlist_memberships')),
    sa.UniqueConstraint('video_id', 'playlist_id', name='uq_youtube_video_playlist_memberships_pair'),
    comment='YouTube视频实际播放列表归属'
    )
    op.create_index('ix_youtube_video_playlist_memberships_playlist', 'youtube_video_playlist_memberships', ['playlist_id', 'status'], unique=False)
    op.create_table('youtube_video_status_history',
    sa.Column('video_id', sa.String(length=36), nullable=False, comment='视频内部ID'),
    sa.Column('old_publish_status', sa.String(length=20), nullable=True, comment='变化前发布状态'),
    sa.Column('new_publish_status', sa.String(length=20), nullable=False, comment='变化后发布状态'),
    sa.Column('old_privacy_status', sa.String(length=20), nullable=True, comment='变化前隐私状态'),
    sa.Column('new_privacy_status', sa.String(length=20), nullable=False, comment='变化后隐私状态'),
    sa.Column('reason', sa.Text(), nullable=False, comment='状态变化原因'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='状态变化来源'),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False, comment='状态变化时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], name=op.f('fk_youtube_video_status_history_video_id_youtube_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_video_status_history')),
    comment='YouTube视频发布状态变化历史'
    )
    op.create_index('ix_youtube_video_status_history_video_time', 'youtube_video_status_history', ['video_id', 'changed_at'], unique=False)
    op.create_table('youtube_comment_replies',
    sa.Column('comment_id', sa.String(length=36), nullable=False, comment='被回复评论内部ID'),
    sa.Column('youtube_reply_id', sa.String(length=120), nullable=True, comment='发布后的YouTube回复ID'),
    sa.Column('reply_text', sa.Text(), nullable=False, comment='频道语言回复正文'),
    sa.Column('reply_translation', sa.Text(), nullable=True, comment='回复中文翻译'),
    sa.Column('generation_method', sa.String(length=20), nullable=False, comment='AI、人工或模板生成'),
    sa.Column('approval_status', sa.String(length=20), nullable=False, comment='审核状态'),
    sa.Column('publish_status', sa.String(length=20), nullable=False, comment='发布状态'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='回复实际发布时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='发布失败脱敏信息'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("approval_status IN ('not_required','pending','approved','rejected')", name=op.f('ck_youtube_comment_replies_valid_approval_status')),
    sa.CheckConstraint("generation_method IN ('ai','manual','template')", name=op.f('ck_youtube_comment_replies_valid_generation_method')),
    sa.CheckConstraint("publish_status IN ('draft','queued','published','failed','cancelled')", name=op.f('ck_youtube_comment_replies_valid_publish_status')),
    sa.ForeignKeyConstraint(['comment_id'], ['youtube_comments.id'], name=op.f('fk_youtube_comment_replies_comment_id_youtube_comments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_comment_replies')),
    sa.UniqueConstraint('youtube_reply_id', name=op.f('uq_youtube_comment_replies_youtube_reply_id')),
    comment='YouTube评论回复版本与发布状态'
    )
    op.create_index('ix_youtube_comment_replies_comment_status', 'youtube_comment_replies', ['comment_id', 'publish_status'], unique=False)
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_youtube_comment_replies_comment_status', table_name='youtube_comment_replies')
    op.drop_table('youtube_comment_replies')
    op.drop_index('ix_youtube_video_status_history_video_time', table_name='youtube_video_status_history')
    op.drop_table('youtube_video_status_history')
    op.drop_index('ix_youtube_video_playlist_memberships_playlist', table_name='youtube_video_playlist_memberships')
    op.drop_table('youtube_video_playlist_memberships')
    op.drop_index('ix_youtube_video_daily_metrics_date', table_name='youtube_video_daily_metrics')
    op.drop_table('youtube_video_daily_metrics')
    op.drop_index('ix_youtube_comments_video_time', table_name='youtube_comments')
    op.drop_index('ix_youtube_comments_channel_reply', table_name='youtube_comments')
    op.drop_table('youtube_comments')
    op.drop_index('ix_youtube_analytics_breakdowns_channel_date', table_name='youtube_analytics_breakdowns')
    op.drop_table('youtube_analytics_breakdowns')
    op.drop_index('ix_youtube_videos_package', table_name='youtube_videos')
    op.drop_index('ix_youtube_videos_channel_status', table_name='youtube_videos')
    op.drop_table('youtube_videos')
    op.drop_index('ix_quota_usage_logs_date_channel', table_name='quota_usage_logs')
    op.drop_table('quota_usage_logs')
    op.drop_index('ix_api_request_logs_data_type_time', table_name='api_request_logs')
    op.drop_index('ix_api_request_logs_channel_time', table_name='api_request_logs')
    op.drop_table('api_request_logs')
    op.drop_index('ix_youtube_channel_daily_metrics_date', table_name='youtube_channel_daily_metrics')
    op.drop_table('youtube_channel_daily_metrics')
    op.drop_index('ix_sync_watermarks_status_lease', table_name='sync_watermarks')
    op.drop_table('sync_watermarks')
    # ### end Alembic commands ###
