"""track playlist membership ordering

Revision ID: 467e92fbfc75
Revises: 38e8492db3c3
Create Date: 2026-08-16 19:19:53.901339
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '467e92fbfc75'
down_revision: Union[str, None] = '38e8492db3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_playlist_order_history',
    sa.Column('membership_id', sa.String(length=36), nullable=False, comment='视频播放列表归属ID'),
    sa.Column('playlist_id', sa.String(length=36), nullable=False, comment='播放列表内部ID'),
    sa.Column('video_id', sa.String(length=36), nullable=False, comment='视频内部ID'),
    sa.Column('old_position', sa.Integer(), nullable=True, comment='变更前位置'),
    sa.Column('new_position', sa.Integer(), nullable=True, comment='变更后位置'),
    sa.Column('old_score', sa.Numeric(precision=18, scale=5), nullable=True, comment='变更前排序评分'),
    sa.Column('new_score', sa.Numeric(precision=18, scale=5), nullable=True, comment='变更后排序评分'),
    sa.Column('old_status', sa.String(length=20), nullable=True, comment='变更前归属状态'),
    sa.Column('new_status', sa.String(length=20), nullable=False, comment='变更后归属状态'),
    sa.Column('reason', sa.Text(), nullable=False, comment='排序或归属变化原因'),
    sa.Column('actor_type', sa.String(length=40), nullable=False, comment='操作者类型'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='操作者内部ID'),
    sa.Column('changed_at', mysql.DATETIME(fsp=6), nullable=False, comment='变更时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.CheckConstraint("new_status IN ('active','removed')", name=op.f('ck_youtube_playlist_order_history_valid_new_status')),
    sa.CheckConstraint("old_status IS NULL OR old_status IN ('active','removed')", name=op.f('ck_youtube_playlist_order_history_valid_old_status')),
    sa.CheckConstraint('new_position IS NULL OR new_position >= 0', name=op.f('ck_youtube_playlist_order_history_new_position_nonnegative')),
    sa.CheckConstraint('new_score IS NULL OR new_score >= 0', name=op.f('ck_youtube_playlist_order_history_new_score_nonnegative')),
    sa.CheckConstraint('old_position IS NULL OR old_position >= 0', name=op.f('ck_youtube_playlist_order_history_old_position_nonnegative')),
    sa.CheckConstraint('old_score IS NULL OR old_score >= 0', name=op.f('ck_youtube_playlist_order_history_old_score_nonnegative')),
    sa.ForeignKeyConstraint(['membership_id'], ['youtube_video_playlist_memberships.id'], name=op.f('fk_youtube_playlist_order_history_membership_id_youtube_video_playlist_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['channel_playlists.id'], name=op.f('fk_youtube_playlist_order_history_playlist_id_channel_playlists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], name=op.f('fk_youtube_playlist_order_history_video_id_youtube_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_playlist_order_history')),
    comment='播放列表视频位置、评分和归属状态变更历史'
    )
    op.create_index('ix_youtube_playlist_order_history_membership_time', 'youtube_playlist_order_history', ['membership_id', 'changed_at'], unique=False)
    op.create_index('ix_youtube_playlist_order_history_playlist_time', 'youtube_playlist_order_history', ['playlist_id', 'changed_at'], unique=False)
    op.add_column('youtube_video_playlist_memberships', sa.Column('score', sa.Numeric(precision=18, scale=5), nullable=True, comment='当前动态排序综合评分'))
    op.add_column('youtube_video_playlist_memberships', sa.Column('source', sa.String(length=30), server_default='youtube_sync', nullable=False, comment='人工、YouTube同步或分析重排来源'))
    op.create_check_constraint(op.f('ck_youtube_video_playlist_memberships_score_nonnegative'), 'youtube_video_playlist_memberships', 'score IS NULL OR score >= 0')
    op.create_check_constraint(op.f('ck_youtube_video_playlist_memberships_valid_source'), 'youtube_video_playlist_memberships', "source IN ('manual','youtube_sync','analytics_reorder')")
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_youtube_video_playlist_memberships_valid_source'), 'youtube_video_playlist_memberships', type_='check')
    op.drop_constraint(op.f('ck_youtube_video_playlist_memberships_score_nonnegative'), 'youtube_video_playlist_memberships', type_='check')
    op.drop_column('youtube_video_playlist_memberships', 'source')
    op.drop_column('youtube_video_playlist_memberships', 'score')
    op.drop_index('ix_youtube_playlist_order_history_playlist_time', table_name='youtube_playlist_order_history')
    op.drop_index('ix_youtube_playlist_order_history_membership_time', table_name='youtube_playlist_order_history')
    op.drop_table('youtube_playlist_order_history')
    # ### end Alembic commands ###
