"""add channel intelligence and integrations

Revision ID: 47578728d684
Revises: 9f727ec0b781
Create Date: 2026-08-16 17:16:05.778547
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '47578728d684'
down_revision: Union[str, None] = '9f727ec0b781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER TABLE channels DROP CHECK ck_channels_valid_status"))
    op.create_table('integrations',
    sa.Column('code', sa.String(length=60), nullable=False, comment='系统内稳定集成代码'),
    sa.Column('name', sa.String(length=120), nullable=False, comment='集成显示名称'),
    sa.Column('provider_type', sa.String(length=60), nullable=False, comment='服务提供方类型'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='集成状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','disabled','deprecated')", name=op.f('ck_integrations_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('code', name=op.f('uq_integrations_code')),
    comment='第三方服务类型定义'
    )
    op.create_table('channel_analysis_reports',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('report_type', sa.String(length=20), nullable=False, comment='报告类型'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True, comment='分析周期开始时间'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True, comment='分析周期结束时间'),
    sa.Column('summary', sa.Text(), nullable=True, comment='报告摘要'),
    sa.Column('growth_reasons', sa.Text(), nullable=True, comment='增长原因'),
    sa.Column('decline_reasons', sa.Text(), nullable=True, comment='下降原因'),
    sa.Column('primary_content', sa.Text(), nullable=True, comment='主材分析'),
    sa.Column('supporting_content', sa.Text(), nullable=True, comment='辅材分析'),
    sa.Column('risks', sa.Text(), nullable=True, comment='风险分析'),
    sa.Column('recommendations', sa.Text(), nullable=True, comment='下一步建议'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='报告状态'),
    sa.Column('generated_by', sa.String(length=40), server_default='system', nullable=False, comment='报告生成方式'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("report_type IN ('initial','periodic','manual','incident')", name=op.f('ck_channel_analysis_reports_valid_report_type')),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','archived')", name=op.f('ck_channel_analysis_reports_valid_status')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_analysis_reports_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_analysis_reports')),
    comment='频道分析报告及其历史版本'
    )
    op.create_index('ix_channel_analysis_reports_channel_period', 'channel_analysis_reports', ['channel_id', 'period_end', 'status'], unique=False)
    op.create_table('channel_keywords',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('keyword', sa.String(length=255), nullable=False, comment='关键词或标签正文'),
    sa.Column('keyword_type', sa.String(length=20), nullable=False, comment='词条类型'),
    sa.Column('language', sa.String(length=20), nullable=False, comment='词条语言'),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), server_default='0.5000', nullable=False, comment='词条权重，0到1'),
    sa.Column('source', sa.String(length=60), nullable=False, comment='词条来源'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='失效时间'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='词条状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("keyword_type IN ('keyword','tag')", name=op.f('ck_channel_keywords_valid_keyword_type')),
    sa.CheckConstraint("status IN ('active','inactive','archived')", name=op.f('ck_channel_keywords_valid_status')),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_channel_keywords_weight_range')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_keywords_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_keywords')),
    sa.UniqueConstraint('channel_id', 'keyword', 'keyword_type', 'language', name='uq_channel_keywords_identity'),
    comment='频道关键词与标签明细'
    )
    op.create_index('ix_channel_keywords_channel_status', 'channel_keywords', ['channel_id', 'status', 'keyword_type'], unique=False)
    op.create_table('integration_accounts',
    sa.Column('integration_id', sa.String(length=36), nullable=False, comment='第三方集成ID'),
    sa.Column('account_key', sa.String(length=255), nullable=False, comment='系统内账号稳定标识'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='账号显示名称'),
    sa.Column('external_account_id', sa.String(length=255), nullable=True, comment='第三方平台账号ID'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='账号连接状态'),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True, comment='最后验证时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('pending','active','expired','revoked','error','disabled')", name=op.f('ck_integration_accounts_valid_status')),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_integration_accounts_integration_id_integrations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_accounts')),
    sa.UniqueConstraint('integration_id', 'account_key', name='uq_integration_accounts_key'),
    comment='第三方服务中的具体账号'
    )
    op.create_index('ix_integration_accounts_integration_status', 'integration_accounts', ['integration_id', 'status'], unique=False)
    op.create_table('media_assets',
    sa.Column('channel_id', sa.String(length=36), nullable=True, comment='所属频道内部ID'),
    sa.Column('storage_provider', sa.String(length=40), nullable=False, comment='存储提供方，如local或s3'),
    sa.Column('storage_key', sa.String(length=600), nullable=False, comment='存储系统内稳定对象键'),
    sa.Column('original_filename', sa.String(length=500), nullable=True, comment='上传时原始文件名'),
    sa.Column('asset_type', sa.String(length=20), nullable=False, comment='资产大类'),
    sa.Column('mime_type', sa.String(length=150), nullable=True, comment='MIME类型'),
    sa.Column('sha256', sa.String(length=64), nullable=False, comment='文件SHA-256摘要'),
    sa.Column('width', sa.Integer(), nullable=True, comment='图片或视频宽度像素'),
    sa.Column('height', sa.Integer(), nullable=True, comment='图片或视频高度像素'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False, comment='文件大小字节数'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='资产状态'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("asset_type IN ('image','video','audio','document','other')", name=op.f('ck_media_assets_valid_asset_type')),
    sa.CheckConstraint("status IN ('pending','ready','failed','archived','deleted')", name=op.f('ck_media_assets_valid_status')),
    sa.CheckConstraint('file_size_bytes >= 0', name=op.f('ck_media_assets_file_size_nonnegative')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_media_assets_channel_id_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_provider', 'storage_key', name='uq_media_assets_storage_location'),
    comment='图片、视频和文档等媒体资产元数据'
    )
    op.create_index('ix_media_assets_channel_status', 'media_assets', ['channel_id', 'status'], unique=False)
    op.create_index('ix_media_assets_sha256', 'media_assets', ['sha256'], unique=False)
    op.create_table('channel_branding_assets',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('asset_id', sa.String(length=36), nullable=False, comment='媒体资产ID'),
    sa.Column('role', sa.String(length=30), nullable=False, comment='装潢资产用途'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='使用状态'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='失效时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("role IN ('avatar','banner','watermark','community_default')", name=op.f('ck_channel_branding_assets_valid_role')),
    sa.CheckConstraint("status IN ('draft','active','superseded','archived')", name=op.f('ck_channel_branding_assets_valid_status')),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], name=op.f('fk_channel_branding_assets_asset_id_media_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_branding_assets_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_branding_assets')),
    comment='频道装潢资产使用历史'
    )
    op.create_index('ix_channel_branding_assets_channel_role', 'channel_branding_assets', ['channel_id', 'role', 'status'], unique=False)
    op.create_table('channel_dna_versions',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('analysis_report_id', sa.String(length=36), nullable=True, comment='形成该版本的分析报告ID'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='频道内递增版本号'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='DNA版本状态'),
    sa.Column('language', sa.String(length=20), nullable=False, comment='频道语言'),
    sa.Column('primary_genre', sa.String(length=120), nullable=False, comment='主题材'),
    sa.Column('secondary_genre', sa.String(length=255), nullable=True, comment='子题材'),
    sa.Column('audience_summary', sa.Text(), nullable=True, comment='核心受众描述'),
    sa.Column('age_tendency', sa.String(length=120), nullable=True, comment='年龄倾向'),
    sa.Column('gender_tendency', sa.String(length=120), nullable=True, comment='性别倾向'),
    sa.Column('emotion_preference', sa.Text(), nullable=True, comment='情绪偏好'),
    sa.Column('plot_preference', sa.Text(), nullable=True, comment='剧情偏好'),
    sa.Column('character_preference', sa.Text(), nullable=True, comment='人物偏好'),
    sa.Column('conflict_preference', sa.Text(), nullable=True, comment='冲突偏好'),
    sa.Column('title_style', sa.Text(), nullable=True, comment='标题风格'),
    sa.Column('cover_style', sa.Text(), nullable=True, comment='封面风格'),
    sa.Column('community_style', sa.Text(), nullable=True, comment='Community风格'),
    sa.Column('content_pace', sa.Text(), nullable=True, comment='内容节奏'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='失效时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('draft','active','superseded','archived')", name=op.f('ck_channel_dna_versions_valid_status')),
    sa.ForeignKeyConstraint(['analysis_report_id'], ['channel_analysis_reports.id'], name=op.f('fk_channel_dna_versions_analysis_report_id_channel_analysis_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_dna_versions_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_dna_versions')),
    sa.UniqueConstraint('channel_id', 'version_number', name='uq_channel_dna_versions_number'),
    comment='可追溯的频道DNA版本'
    )
    op.create_index('ix_channel_dna_versions_channel_status', 'channel_dna_versions', ['channel_id', 'status'], unique=False)
    op.create_table('channel_profiles',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('avatar_asset_id', sa.String(length=36), nullable=True, comment='当前头像资产ID'),
    sa.Column('banner_asset_id', sa.String(length=36), nullable=True, comment='当前Banner资产ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='频道说明'),
    sa.Column('language', sa.String(length=20), nullable=True, comment='频道展示语言'),
    sa.Column('positioning', sa.Text(), nullable=True, comment='频道定位说明'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='档案状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('draft','active','archived')", name=op.f('ck_channel_profiles_valid_status')),
    sa.ForeignKeyConstraint(['avatar_asset_id'], ['media_assets.id'], name=op.f('fk_channel_profiles_avatar_asset_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['banner_asset_id'], ['media_assets.id'], name=op.f('fk_channel_profiles_banner_asset_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_profiles_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_profiles')),
    sa.UniqueConstraint('channel_id', name='uq_channel_profiles_channel_id'),
    comment='频道当前展示与定位档案'
    )
    op.create_table('integration_credentials',
    sa.Column('integration_account_id', sa.String(length=36), nullable=False, comment='第三方账号ID'),
    sa.Column('credential_type', sa.String(length=60), nullable=False, comment='凭证类型'),
    sa.Column('secret_reference', sa.String(length=500), nullable=False, comment='外部Secret存储引用'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='凭证状态'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='凭证失效时间'),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True, comment='最后验证时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','expired','revoked','error')", name=op.f('ck_integration_credentials_valid_status')),
    sa.ForeignKeyConstraint(['integration_account_id'], ['integration_accounts.id'], name=op.f('fk_integration_credentials_integration_account_id_integration_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_credentials')),
    sa.UniqueConstraint('integration_account_id', 'credential_type', name='uq_integration_credentials_type'),
    comment='第三方账号凭证引用，禁止保存密钥明文'
    )
    op.create_index('ix_integration_credentials_account_status', 'integration_credentials', ['integration_account_id', 'status'], unique=False)
    op.create_table('channel_dna_signals',
    sa.Column('dna_version_id', sa.String(length=36), nullable=False, comment='频道DNA版本ID'),
    sa.Column('signal_type', sa.String(length=30), nullable=False, comment='信号类型'),
    sa.Column('value', sa.String(length=500), nullable=False, comment='关键词或剧情模式正文'),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), server_default='0.5000', nullable=False, comment='信号权重，0到1'),
    sa.Column('rank_number', sa.Integer(), nullable=False, comment='同类信号排序'),
    sa.Column('evidence_summary', sa.Text(), nullable=True, comment='形成该判断的证据摘要'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("signal_type IN ('high_keyword','low_keyword','high_plot_pattern','low_plot_pattern')", name=op.f('ck_channel_dna_signals_valid_signal_type')),
    sa.CheckConstraint('rank_number >= 1', name=op.f('ck_channel_dna_signals_rank_positive')),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_channel_dna_signals_weight_range')),
    sa.ForeignKeyConstraint(['dna_version_id'], ['channel_dna_versions.id'], name=op.f('fk_channel_dna_signals_dna_version_id_channel_dna_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_dna_signals')),
    sa.UniqueConstraint('dna_version_id', 'signal_type', 'value', name='uq_channel_dna_signals_identity'),
    comment='频道DNA中的高低表现关键词和剧情模式'
    )
    op.create_index('ix_channel_dna_signals_version_type', 'channel_dna_signals', ['dna_version_id', 'signal_type', 'rank_number'], unique=False)
    op.alter_column('channels', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default='new',
               comment='频道生命周期状态',
               existing_comment='频道状态',
               existing_nullable=False,
               existing_server_default=sa.text("'onboarding'"))
    op.execute(sa.text("""
        ALTER TABLE channels ADD CONSTRAINT ck_channels_valid_status
        CHECK (status IN ('new','authorized','analyzed','branded','configured','scheduled','active','paused','archived','deleted'))
    """))
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER TABLE channels DROP CHECK ck_channels_valid_status"))
    op.alter_column('channels', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default='onboarding',
               comment='频道状态',
               existing_comment='频道生命周期状态',
               existing_nullable=False,
               existing_server_default=sa.text("'new'"))
    op.execute(sa.text("""
        ALTER TABLE channels ADD CONSTRAINT ck_channels_valid_status
        CHECK (status IN ('onboarding','active','paused','archived','deleted'))
    """))
    op.drop_index('ix_channel_dna_signals_version_type', table_name='channel_dna_signals')
    op.drop_table('channel_dna_signals')
    op.drop_index('ix_integration_credentials_account_status', table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_table('channel_profiles')
    op.drop_index('ix_channel_dna_versions_channel_status', table_name='channel_dna_versions')
    op.drop_table('channel_dna_versions')
    op.drop_index('ix_channel_branding_assets_channel_role', table_name='channel_branding_assets')
    op.drop_table('channel_branding_assets')
    op.drop_index('ix_media_assets_sha256', table_name='media_assets')
    op.drop_index('ix_media_assets_channel_status', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_integration_accounts_integration_status', table_name='integration_accounts')
    op.drop_table('integration_accounts')
    op.drop_index('ix_channel_keywords_channel_status', table_name='channel_keywords')
    op.drop_table('channel_keywords')
    op.drop_index('ix_channel_analysis_reports_channel_period', table_name='channel_analysis_reports')
    op.drop_table('channel_analysis_reports')
    op.drop_table('integrations')
    # ### end Alembic commands ###
