"""close youtube publication feedback loop

Revision ID: 8448b607e05f
Revises: 9a504eb5d9fb
Create Date: 2026-08-17 00:06:49.336415
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8448b607e05f'
down_revision: Union[str, None] = '9a504eb5d9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_youtube_videos_operation_package', 'youtube_videos', ['operation_package_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_youtube_videos_operation_package', 'youtube_videos', type_='unique')
    # ### end Alembic commands ###

