"""add drama library playlists and schedules

Revision ID: 8841dc7f90bc
Revises: 47578728d684
Create Date: 2026-08-16 17:32:39.567825
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8841dc7f90bc'
down_revision: Union[str, None] = '47578728d684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dramas',
    sa.Column('drama_code', sa.String(length=40), nullable=False, comment='系统自动生成的可读剧库ID'),
    sa.Column('chinese_title', sa.String(length=255), nullable=False, comment='中文主剧名'),
    sa.Column('normalized_title', sa.String(length=255), nullable=False, comment='用于完全匹配的规范化主剧名'),
    sa.Column('baidu_cloud_url', sa.String(length=1000), nullable=True, comment='百度网盘资源地址'),
    sa.Column('content_summary', sa.Text(), nullable=True, comment='内容概要'),
    sa.Column('plot_archive', sa.Text(), nullable=True, comment='剧情档案'),
    sa.Column('plot_pattern', sa.Text(), nullable=True, comment='剧情套路'),
    sa.Column('core_personas', sa.Text(), nullable=True, comment='核心人设'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='剧目资源到期时间'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='剧目状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','expired','blocked','archived')", name=op.f('ck_dramas_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dramas')),
    sa.UniqueConstraint('drama_code', name=op.f('uq_dramas_drama_code')),
    sa.UniqueConstraint('normalized_title', name=op.f('uq_dramas_normalized_title')),
    comment='本地剧库中的剧目主档'
    )
    op.create_index('ix_dramas_status_expiry', 'dramas', ['status', 'expires_at'], unique=False)
    op.create_table('languages',
    sa.Column('code', sa.String(length=20), nullable=False, comment='BCP 47语言代码'),
    sa.Column('name_zh', sa.String(length=120), nullable=False, comment='中文语言名称'),
    sa.Column('native_name', sa.String(length=120), nullable=True, comment='语言本地名称'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='语言状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','inactive')", name=op.f('ck_languages_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('code', name=op.f('uq_languages_code')),
    comment='系统支持的语言定义'
    )
    op.create_table('channel_playlists',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('youtube_playlist_id', sa.String(length=80), nullable=True, comment='YouTube播放列表外部ID'),
    sa.Column('local_name', sa.String(length=255), nullable=False, comment='目标语言播放列表名称'),
    sa.Column('chinese_name', sa.String(length=255), nullable=True, comment='播放列表中文名称'),
    sa.Column('local_description', sa.Text(), nullable=True, comment='目标语言播放列表说明'),
    sa.Column('chinese_description', sa.Text(), nullable=True, comment='播放列表中文说明'),
    sa.Column('url', sa.String(length=1000), nullable=True, comment='YouTube播放列表地址'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='频道内显示排序'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='播放列表状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('draft','active','paused','archived','deleted')", name=op.f('ck_channel_playlists_valid_status')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_channel_playlists_sort_order_nonnegative')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_playlists_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_playlists')),
    sa.UniqueConstraint('channel_id', 'local_name', name='uq_channel_playlists_local_name'),
    sa.UniqueConstraint('youtube_playlist_id', name=op.f('uq_channel_playlists_youtube_playlist_id')),
    comment='频道播放列表定义'
    )
    op.create_index('ix_channel_playlists_channel_status', 'channel_playlists', ['channel_id', 'status', 'sort_order'], unique=False)
    op.create_table('channel_publish_slots',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('slot_type', sa.String(length=20), nullable=False, comment='主档或辅档'),
    sa.Column('slot_number', sa.SmallInteger(), nullable=False, comment='同类档位编号'),
    sa.Column('local_time', sa.Time(), nullable=False, comment='频道当地发布时间'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='IANA时区'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='档位状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("slot_type IN ('main','aux')", name=op.f('ck_channel_publish_slots_valid_slot_type')),
    sa.CheckConstraint("status IN ('active','inactive','archived')", name=op.f('ck_channel_publish_slots_valid_status')),
    sa.CheckConstraint('slot_number >= 0', name=op.f('ck_channel_publish_slots_slot_number_nonnegative')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_publish_slots_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_publish_slots')),
    sa.UniqueConstraint('channel_id', 'slot_type', 'slot_number', name='uq_channel_publish_slots_identity'),
    comment='频道长期视频发布时间档位规则'
    )
    op.create_index('ix_channel_publish_slots_channel_status', 'channel_publish_slots', ['channel_id', 'status', 'slot_type', 'slot_number'], unique=False)
    op.create_table('drama_aliases',
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='剧目内部ID'),
    sa.Column('alias', sa.String(length=255), nullable=False, comment='剧目别名'),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False, comment='用于完全匹配的规范化别名'),
    sa.Column('source', sa.String(length=60), server_default='manual', nullable=False, comment='别名来源'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_drama_aliases_drama_id_dramas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drama_aliases')),
    sa.UniqueConstraint('normalized_alias', name='uq_drama_aliases_normalized_alias'),
    comment='剧目别名，一条记录保存一个别名'
    )
    op.create_index('ix_drama_aliases_normalized_alias', 'drama_aliases', ['normalized_alias'], unique=False)
    op.create_table('drama_core_terms',
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='剧目内部ID'),
    sa.Column('term_type', sa.String(length=20), nullable=False, comment='核心词类型'),
    sa.Column('term', sa.String(length=255), nullable=False, comment='核心词正文'),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), server_default='0.5000', nullable=False, comment='核心词权重，0到1'),
    sa.Column('source', sa.String(length=60), server_default='manual', nullable=False, comment='核心词来源'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("term_type IN ('keyword','topic','trope','persona','conflict')", name=op.f('ck_drama_core_terms_valid_term_type')),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_drama_core_terms_drama_id_dramas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drama_core_terms')),
    sa.UniqueConstraint('drama_id', 'term_type', 'term', name='uq_drama_core_terms_identity'),
    comment='剧目核心词、题材、套路、人设和冲突词'
    )
    op.create_index('ix_drama_core_terms_drama_type', 'drama_core_terms', ['drama_id', 'term_type'], unique=False)
    op.create_table('drama_translations',
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='剧目内部ID'),
    sa.Column('language_id', sa.String(length=36), nullable=False, comment='语言内部ID'),
    sa.Column('translated_title', sa.String(length=500), nullable=True, comment='该语言剧名'),
    sa.Column('translation_status', sa.String(length=20), server_default='missing', nullable=False, comment='翻译状态'),
    sa.Column('asset_status', sa.String(length=20), server_default='missing', nullable=False, comment='该语言素材状态'),
    sa.Column('resource_uri', sa.String(length=1000), nullable=True, comment='外部资源定位地址'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("asset_status IN ('missing','partial','ready','expired')", name=op.f('ck_drama_translations_valid_asset_status')),
    sa.CheckConstraint("translation_status IN ('missing','pending','in_progress','ready','failed')", name=op.f('ck_drama_translations_valid_translation_status')),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_drama_translations_drama_id_dramas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_drama_translations_language_id_languages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drama_translations')),
    sa.UniqueConstraint('drama_id', 'language_id', name='uq_drama_translations_language'),
    comment='剧目各语言翻译与素材可用状态'
    )
    op.create_index('ix_drama_translations_language_status', 'drama_translations', ['language_id', 'translation_status', 'asset_status'], unique=False)
    op.create_table('channel_community_slots',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('publish_slot_id', sa.String(length=36), nullable=True, comment='相对模式关联的视频档位ID'),
    sa.Column('schedule_mode', sa.String(length=20), nullable=False, comment='相对档位或固定时间模式'),
    sa.Column('local_time', sa.Time(), nullable=True, comment='固定模式的当地发布时间'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='IANA时区'),
    sa.Column('offset_minutes', sa.Integer(), server_default='0', nullable=False, comment='相对视频档位延迟分钟数'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='Community档位状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("(schedule_mode = 'relative' AND publish_slot_id IS NOT NULL) OR (schedule_mode = 'fixed' AND local_time IS NOT NULL)", name=op.f('ck_channel_community_slots_mode_fields_present')),
    sa.CheckConstraint("schedule_mode IN ('relative','fixed')", name=op.f('ck_channel_community_slots_valid_schedule_mode')),
    sa.CheckConstraint("status IN ('active','inactive','archived')", name=op.f('ck_channel_community_slots_valid_status')),
    sa.CheckConstraint('offset_minutes >= 0', name=op.f('ck_channel_community_slots_offset_nonnegative')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_community_slots_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publish_slot_id'], ['channel_publish_slots.id'], name=op.f('fk_channel_community_slots_publish_slot_id_channel_publish_slots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_community_slots')),
    comment='频道Community发布时间规则'
    )
    op.create_index('ix_channel_community_slots_channel_status', 'channel_community_slots', ['channel_id', 'status'], unique=False)
    op.create_table('channel_schedule_entries',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='剧目内部ID'),
    sa.Column('playlist_id', sa.String(length=36), nullable=True, comment='计划加入的播放列表ID'),
    sa.Column('publish_slot_id', sa.String(length=36), nullable=False, comment='发布时间档位ID'),
    sa.Column('publish_date', sa.Date(), nullable=False, comment='频道当地发布日期'),
    sa.Column('planned_local_time', sa.DateTime(timezone=True), nullable=False, comment='固化的当地计划时间'),
    sa.Column('planned_beijing_time', sa.DateTime(timezone=True), nullable=False, comment='固化的北京时间'),
    sa.Column('planned_utc_time', sa.DateTime(timezone=True), nullable=False, comment='固化的UTC时间'),
    sa.Column('community_count', sa.SmallInteger(), server_default='0', nullable=False, comment='计划Community数量'),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False, comment='排期状态'),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False, comment='排期优先级，数值越小越优先'),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False, comment='创建排期的幂等键'),
    sa.Column('replaced_by_schedule_id', sa.String(length=36), nullable=True, comment='替换后的排期ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('planned','reserved','confirmed','replaced','cancelled','published')", name=op.f('ck_channel_schedule_entries_valid_status')),
    sa.CheckConstraint('community_count >= 0', name=op.f('ck_channel_schedule_entries_community_count_nonnegative')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_schedule_entries_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_channel_schedule_entries_drama_id_dramas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['playlist_id'], ['channel_playlists.id'], name=op.f('fk_channel_schedule_entries_playlist_id_channel_playlists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publish_slot_id'], ['channel_publish_slots.id'], name=op.f('fk_channel_schedule_entries_publish_slot_id_channel_publish_slots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaced_by_schedule_id'], ['channel_schedule_entries.id'], name=op.f('fk_channel_schedule_entries_replaced_by_schedule_id_channel_schedule_entries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_schedule_entries')),
    sa.UniqueConstraint('channel_id', 'publish_date', 'publish_slot_id', name='uq_schedule_entries_channel_slot_date'),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_channel_schedule_entries_idempotency_key')),
    comment='频道某日某档位的剧目排期实例'
    )
    op.create_index('ix_schedule_entries_channel_date_status', 'channel_schedule_entries', ['channel_id', 'publish_date', 'status'], unique=False)
    op.create_index('ix_schedule_entries_drama_status', 'channel_schedule_entries', ['drama_id', 'status'], unique=False)
    op.create_table('schedule_candidates',
    sa.Column('schedule_id', sa.String(length=36), nullable=False, comment='排期实例ID'),
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='候选剧目ID'),
    sa.Column('candidate_type', sa.String(length=20), nullable=False, comment='主选或备选'),
    sa.Column('rank_number', sa.Integer(), nullable=False, comment='候选排序'),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True, comment='选剧评分'),
    sa.Column('reason', sa.Text(), nullable=True, comment='入选原因'),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False, comment='候选状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("candidate_type IN ('primary','backup')", name=op.f('ck_schedule_candidates_valid_candidate_type')),
    sa.CheckConstraint("status IN ('available','selected','rejected','unavailable')", name=op.f('ck_schedule_candidates_valid_status')),
    sa.CheckConstraint('rank_number >= 1', name=op.f('ck_schedule_candidates_rank_positive')),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_schedule_candidates_drama_id_dramas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['channel_schedule_entries.id'], name=op.f('fk_schedule_candidates_schedule_id_channel_schedule_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_candidates')),
    sa.UniqueConstraint('schedule_id', 'drama_id', name='uq_schedule_candidates_drama'),
    sa.UniqueConstraint('schedule_id', 'rank_number', name='uq_schedule_candidates_rank'),
    comment='排期的主选与备选剧目'
    )
    op.create_index('ix_schedule_candidates_schedule_status', 'schedule_candidates', ['schedule_id', 'status', 'rank_number'], unique=False)
    op.create_table('schedule_change_history',
    sa.Column('schedule_id', sa.String(length=36), nullable=False, comment='排期实例ID'),
    sa.Column('old_drama_id', sa.String(length=36), nullable=True, comment='调整前剧目ID'),
    sa.Column('new_drama_id', sa.String(length=36), nullable=True, comment='调整后剧目ID'),
    sa.Column('old_planned_utc_time', sa.DateTime(timezone=True), nullable=True, comment='调整前UTC计划时间'),
    sa.Column('new_planned_utc_time', sa.DateTime(timezone=True), nullable=True, comment='调整后UTC计划时间'),
    sa.Column('old_status', sa.String(length=20), nullable=True, comment='调整前状态'),
    sa.Column('new_status', sa.String(length=20), nullable=False, comment='调整后状态'),
    sa.Column('reason', sa.Text(), nullable=False, comment='调整原因'),
    sa.Column('actor_type', sa.String(length=40), nullable=False, comment='操作者类型'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='操作者内部ID'),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False, comment='调整时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.ForeignKeyConstraint(['new_drama_id'], ['dramas.id'], name=op.f('fk_schedule_change_history_new_drama_id_dramas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_drama_id'], ['dramas.id'], name=op.f('fk_schedule_change_history_old_drama_id_dramas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['channel_schedule_entries.id'], name=op.f('fk_schedule_change_history_schedule_id_channel_schedule_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_change_history')),
    comment='排期每次调整的不可变历史'
    )
    op.create_index('ix_schedule_change_history_schedule_time', 'schedule_change_history', ['schedule_id', 'changed_at'], unique=False)
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_change_history_schedule_time', table_name='schedule_change_history')
    op.drop_table('schedule_change_history')
    op.drop_index('ix_schedule_candidates_schedule_status', table_name='schedule_candidates')
    op.drop_table('schedule_candidates')
    op.drop_index('ix_schedule_entries_drama_status', table_name='channel_schedule_entries')
    op.drop_index('ix_schedule_entries_channel_date_status', table_name='channel_schedule_entries')
    op.drop_table('channel_schedule_entries')
    op.drop_index('ix_channel_community_slots_channel_status', table_name='channel_community_slots')
    op.drop_table('channel_community_slots')
    op.drop_index('ix_drama_translations_language_status', table_name='drama_translations')
    op.drop_table('drama_translations')
    op.drop_index('ix_drama_core_terms_drama_type', table_name='drama_core_terms')
    op.drop_table('drama_core_terms')
    op.drop_index('ix_drama_aliases_normalized_alias', table_name='drama_aliases')
    op.drop_table('drama_aliases')
    op.drop_index('ix_channel_publish_slots_channel_status', table_name='channel_publish_slots')
    op.drop_table('channel_publish_slots')
    op.drop_index('ix_channel_playlists_channel_status', table_name='channel_playlists')
    op.drop_table('channel_playlists')
    op.drop_table('languages')
    op.drop_index('ix_dramas_status_expiry', table_name='dramas')
    op.drop_table('dramas')
    # ### end Alembic commands ###
