"""enforce package similarity score ranges

Revision ID: 8e0c7f4c71e9
Revises: cbe100b9853c
Create Date: 2026-08-16 23:02:17.483052
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e0c7f4c71e9'
down_revision: Union[str, None] = 'cbe100b9853c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_package_similarity_checks_valid_cover_similarity'), 'package_similarity_checks', 'cover_similarity IS NULL OR cover_similarity BETWEEN 0 AND 1')
    op.create_check_constraint(op.f('ck_package_similarity_checks_valid_creative_similarity'), 'package_similarity_checks', 'creative_similarity IS NULL OR creative_similarity BETWEEN 0 AND 1')
    op.create_check_constraint(op.f('ck_package_similarity_checks_valid_description_similarity'), 'package_similarity_checks', 'description_similarity IS NULL OR description_similarity BETWEEN 0 AND 1')
    op.create_check_constraint(op.f('ck_package_similarity_checks_valid_title_similarity'), 'package_similarity_checks', 'title_similarity IS NULL OR title_similarity BETWEEN 0 AND 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_package_similarity_checks_valid_title_similarity'), 'package_similarity_checks', type_='check')
    op.drop_constraint(op.f('ck_package_similarity_checks_valid_description_similarity'), 'package_similarity_checks', type_='check')
    op.drop_constraint(op.f('ck_package_similarity_checks_valid_creative_similarity'), 'package_similarity_checks', type_='check')
    op.drop_constraint(op.f('ck_package_similarity_checks_valid_cover_similarity'), 'package_similarity_checks', type_='check')
    # ### end Alembic commands ###

