"""complete media asset registry

Revision ID: 9a504eb5d9fb
Revises: 107204d31ece
Create Date: 2026-08-16 23:59:27.129440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a504eb5d9fb'
down_revision: Union[str, None] = '107204d31ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('asset_role', sa.String(length=40), server_default='other', nullable=False, comment='资产业务用途'))
    op.add_column('media_assets', sa.Column('public_url', sa.String(length=1000), nullable=True, comment='可公开访问地址'))
    op.create_check_constraint(op.f('ck_media_assets_valid_asset_role'), 'media_assets', "asset_role IN ('channel_avatar','channel_banner','channel_watermark','thumbnail','community_image','source_material','package_artifact','other')")
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name = 'media_assets'
          AND column_name IN ('asset_role', 'public_url')
          AND column_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text(
        "DELETE FROM schema_comments WHERE table_name = 'media_assets' "
        "AND column_name IN ('asset_role', 'public_url')"
    ))
    op.drop_constraint(op.f('ck_media_assets_valid_asset_role'), 'media_assets', type_='check')
    op.drop_column('media_assets', 'public_url')
    op.drop_column('media_assets', 'asset_role')
    # ### end Alembic commands ###
