"""create identity and channel foundation

Revision ID: 9f727ec0b781
Revises: 
Create Date: 2026-08-16 01:39:20.112947
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f727ec0b781'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_type', sa.String(length=40), nullable=False, comment='操作者类型'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='操作者内部ID'),
    sa.Column('action', sa.String(length=80), nullable=False, comment='操作动作'),
    sa.Column('entity_type', sa.String(length=80), nullable=False, comment='业务对象类型'),
    sa.Column('entity_id', sa.String(length=36), nullable=False, comment='业务对象内部ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求追踪ID'),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True, comment='幂等键'),
    sa.Column('change_summary', sa.Text(), nullable=True, comment='不含密钥的变更摘要'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='操作发生时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_audit_events_idempotency_key')),
    comment='业务对象变更审计流水'
    )
    op.create_index('ix_audit_events_actor_time', 'audit_events', ['actor_type', 'actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_entity_time', 'audit_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_table('channels',
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False, comment='YouTube频道外部ID'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='YouTube频道原名'),
    sa.Column('operational_name', sa.String(length=255), nullable=True, comment='运营昵称'),
    sa.Column('default_language', sa.String(length=20), nullable=True, comment='默认语言代码'),
    sa.Column('default_genre', sa.String(length=120), nullable=True, comment='默认题材'),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Shanghai', nullable=False, comment='IANA时区'),
    sa.Column('daily_publish_count', sa.SmallInteger(), server_default='0', nullable=False, comment='每日更新次数'),
    sa.Column('status', sa.String(length=20), server_default='onboarding', nullable=False, comment='频道状态'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('onboarding','active','paused','archived','deleted')", name=op.f('ck_channels_valid_status')),
    sa.CheckConstraint('daily_publish_count >= 0', name=op.f('ck_channels_daily_publish_count_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('youtube_channel_id', name=op.f('uq_channels_youtube_channel_id')),
    comment='YouTube频道稳定身份信息'
    )
    op.create_index('ix_channels_status_language', 'channels', ['status', 'default_language'], unique=False)
    op.create_table('devices',
    sa.Column('device_key', sa.String(length=120), nullable=False, comment='设备稳定标识'),
    sa.Column('name', sa.String(length=120), nullable=False, comment='设备名称'),
    sa.Column('alias', sa.String(length=120), nullable=True, comment='设备运营别名'),
    sa.Column('hostname', sa.String(length=255), nullable=False, comment='设备主机名'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='最近一次IP地址'),
    sa.Column('ssh_address', sa.String(length=255), nullable=True, comment='SSH连接地址'),
    sa.Column('os_type', sa.String(length=40), nullable=False, comment='操作系统类型'),
    sa.Column('purpose', sa.String(length=255), nullable=True, comment='设备用途'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='设备状态'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='最后在线时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','inactive','retired')", name=op.f('ck_devices_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_key', name=op.f('uq_devices_device_key')),
    comment='运行、登录或执行授权操作的设备'
    )
    op.create_index('ix_devices_status_last_seen', 'devices', ['status', 'last_seen_at'], unique=False)
    op.create_table('google_accounts',
    sa.Column('nickname', sa.String(length=120), nullable=False, comment='账号运营昵称'),
    sa.Column('google_email', sa.String(length=320), nullable=False, comment='Google账号邮箱'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='账号状态'),
    sa.Column('authorization_status', sa.String(length=20), server_default='pending', nullable=False, comment='授权状态'),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True, comment='首次授权成功时间'),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True, comment='最后验证授权时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("authorization_status IN ('pending','authorized','expired','revoked','error')", name=op.f('ck_google_accounts_valid_authorization_status')),
    sa.CheckConstraint("status IN ('active','disabled','revoked')", name=op.f('ck_google_accounts_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_accounts')),
    sa.UniqueConstraint('google_email', name=op.f('uq_google_accounts_google_email')),
    comment='YouTube授权所使用的Google主账号'
    )
    op.create_index('ix_google_accounts_status_auth', 'google_accounts', ['status', 'authorization_status'], unique=False)
    op.create_table('schema_comments',
    sa.Column('table_name', sa.String(length=128), nullable=False, comment='表名'),
    sa.Column('column_name', sa.String(length=128), nullable=False, comment='字段名，表说明使用__table__'),
    sa.Column('chinese_comment', sa.Text(), nullable=False, comment='中文说明'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('table_name', 'column_name', name=op.f('pk_schema_comments')),
    comment='数据库表字段中文说明'
    )
    op.create_table('google_oauth_grants',
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Google账号内部ID'),
    sa.Column('provider_subject', sa.String(length=255), nullable=False, comment='Google OAuth subject标识'),
    sa.Column('credential_ref', sa.String(length=500), nullable=False, comment='外部Secret存储引用，禁止存Token明文'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='授权记录状态'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='访问令牌预计失效时间'),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True, comment='最后刷新时间'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('pending','active','expired','revoked','error')", name=op.f('ck_google_oauth_grants_valid_status')),
    sa.ForeignKeyConstraint(['account_id'], ['google_accounts.id'], name=op.f('fk_google_oauth_grants_account_id_google_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_oauth_grants')),
    sa.UniqueConstraint('account_id', 'provider_subject', name='uq_oauth_grants_account_subject'),
    comment='Google OAuth授权记录，仅保存Secret引用'
    )
    op.create_index('ix_oauth_grants_account_status', 'google_oauth_grants', ['account_id', 'status'], unique=False)
    op.create_table('account_channel_authorizations',
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Google账号内部ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('oauth_grant_id', sa.String(length=36), nullable=False, comment='实际使用的OAuth授权ID'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='绑定状态'),
    sa.Column('verified_youtube_channel_id', sa.String(length=64), nullable=False, comment='Token调用YouTube后返回的频道ID'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False, comment='频道绑定校验时间'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='解除绑定时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('active','revoked','mismatch','error')", name=op.f('ck_account_channel_authorizations_valid_status')),
    sa.ForeignKeyConstraint(['account_id'], ['google_accounts.id'], name=op.f('fk_account_channel_authorizations_account_id_google_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_account_channel_authorizations_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['oauth_grant_id'], ['google_oauth_grants.id'], name=op.f('fk_account_channel_authorizations_oauth_grant_id_google_oauth_grants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_channel_authorizations')),
    sa.UniqueConstraint('account_id', 'channel_id', name='uq_account_channel_authorizations_pair'),
    comment='Google账号与YouTube频道的授权关系'
    )
    op.create_index('ix_account_channel_auth_channel_status', 'account_channel_authorizations', ['channel_id', 'status'], unique=False)
    op.create_table('authorization_events',
    sa.Column('account_id', sa.String(length=36), nullable=True, comment='Google账号内部ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=True, comment='频道内部ID'),
    sa.Column('device_id', sa.String(length=36), nullable=True, comment='操作设备ID'),
    sa.Column('oauth_grant_id', sa.String(length=36), nullable=True, comment='OAuth授权记录ID'),
    sa.Column('event_type', sa.String(length=60), nullable=False, comment='授权事件类型'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='执行结果'),
    sa.Column('error_code', sa.String(length=120), nullable=True, comment='错误代码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='脱敏错误信息'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='事件发生时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.CheckConstraint("result IN ('success','failure','cancelled')", name=op.f('ck_authorization_events_valid_result')),
    sa.ForeignKeyConstraint(['account_id'], ['google_accounts.id'], name=op.f('fk_authorization_events_account_id_google_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_authorization_events_channel_id_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_authorization_events_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['oauth_grant_id'], ['google_oauth_grants.id'], name=op.f('fk_authorization_events_oauth_grant_id_google_oauth_grants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authorization_events')),
    comment='OAuth授权与频道校验事件流水'
    )
    op.create_index('ix_authorization_events_account_time', 'authorization_events', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_authorization_events_channel_time', 'authorization_events', ['channel_id', 'occurred_at'], unique=False)
    op.create_table('google_oauth_grant_scopes',
    sa.Column('grant_id', sa.String(length=36), nullable=False, comment='OAuth授权记录ID'),
    sa.Column('scope', sa.String(length=500), nullable=False, comment='OAuth scope'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['grant_id'], ['google_oauth_grants.id'], name=op.f('fk_google_oauth_grant_scopes_grant_id_google_oauth_grants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grant_id', 'scope', name=op.f('pk_google_oauth_grant_scopes')),
    comment='OAuth授权范围明细'
    )
    op.execute(sa.text("""
        INSERT INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_oauth_grant_scopes')
    op.drop_index('ix_authorization_events_channel_time', table_name='authorization_events')
    op.drop_index('ix_authorization_events_account_time', table_name='authorization_events')
    op.drop_table('authorization_events')
    op.drop_index('ix_account_channel_auth_channel_status', table_name='account_channel_authorizations')
    op.drop_table('account_channel_authorizations')
    op.drop_index('ix_oauth_grants_account_status', table_name='google_oauth_grants')
    op.drop_table('google_oauth_grants')
    op.drop_table('schema_comments')
    op.drop_index('ix_google_accounts_status_auth', table_name='google_accounts')
    op.drop_table('google_accounts')
    op.drop_index('ix_devices_status_last_seen', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_channels_status_language', table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_audit_events_entity_time', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_time', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
