"""add idempotent youtube api request key

Revision ID: b5f39ba72e31
Revises: 8e0c7f4c71e9
Create Date: 2026-08-16 23:42:08.506705
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5f39ba72e31'
down_revision: Union[str, None] = '8e0c7f4c71e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_request_logs', sa.Column('request_key', sa.String(length=180), nullable=False, comment='调用方生成的API请求幂等键'))
    op.create_unique_constraint(op.f('uq_api_request_logs_request_key'), 'api_request_logs', ['request_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_api_request_logs_request_key'), 'api_request_logs', type_='unique')
    op.drop_column('api_request_logs', 'request_key')
    # ### end Alembic commands ###

