"""add task work order and package factory

Revision ID: c317a2aa1936
Revises: 8841dc7f90bc
Create Date: 2026-08-16 17:41:29.795091
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c317a2aa1936'
down_revision: Union[str, None] = '8841dc7f90bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_events',
    sa.Column('entity_type', sa.String(length=80), nullable=False, comment='业务对象类型'),
    sa.Column('entity_id', sa.String(length=36), nullable=False, comment='业务对象ID'),
    sa.Column('old_status', sa.String(length=40), nullable=True, comment='变化前状态'),
    sa.Column('new_status', sa.String(length=40), nullable=False, comment='变化后状态'),
    sa.Column('reason', sa.Text(), nullable=False, comment='状态变化原因'),
    sa.Column('actor_type', sa.String(length=40), nullable=False, comment='操作者类型'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='操作者ID'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='事件发生时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events')),
    comment='跨业务实体的统一状态事件账本'
    )
    op.create_index('ix_system_events_entity_time', 'system_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_table('operation_tasks',
    sa.Column('schedule_id', sa.String(length=36), nullable=True, comment='来源排期ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='剧目内部ID'),
    sa.Column('publish_slot_id', sa.String(length=36), nullable=True, comment='发布时间档位ID'),
    sa.Column('playlist_id', sa.String(length=36), nullable=True, comment='计划播放列表ID'),
    sa.Column('task_date', sa.Date(), nullable=False, comment='任务生产日期'),
    sa.Column('target_publish_date', sa.Date(), nullable=False, comment='目标发布日期'),
    sa.Column('community_count', sa.SmallInteger(), server_default='0', nullable=False, comment='Community生产数量'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='任务来源'),
    sa.Column('status', sa.String(length=30), server_default='pending_dispatch', nullable=False, comment='任务状态'),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False, comment='任务创建幂等键'),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True, comment='任务下发时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='任务完成时间'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='任务失败原因'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("source IN ('manual','schedule','import')", name=op.f('ck_operation_tasks_valid_source')),
    sa.CheckConstraint("status IN ('pending_dispatch','dispatched','processing','completed','failed','cancelled')", name=op.f('ck_operation_tasks_valid_status')),
    sa.CheckConstraint('community_count >= 0', name=op.f('ck_operation_tasks_community_count_nonnegative')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_operation_tasks_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_operation_tasks_drama_id_dramas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['playlist_id'], ['channel_playlists.id'], name=op.f('fk_operation_tasks_playlist_id_channel_playlists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publish_slot_id'], ['channel_publish_slots.id'], name=op.f('fk_operation_tasks_publish_slot_id_channel_publish_slots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['channel_schedule_entries.id'], name=op.f('fk_operation_tasks_schedule_id_channel_schedule_entries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_tasks')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_operation_tasks_idempotency_key')),
    sa.UniqueConstraint('schedule_id', name='uq_operation_tasks_schedule_id'),
    comment='今日任务及历史任务主记录'
    )
    op.create_index('ix_operation_tasks_channel_status', 'operation_tasks', ['channel_id', 'status'], unique=False)
    op.create_index('ix_operation_tasks_date_status', 'operation_tasks', ['task_date', 'status'], unique=False)
    op.create_table('task_events',
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='任务ID'),
    sa.Column('old_status', sa.String(length=30), nullable=True, comment='变化前状态'),
    sa.Column('new_status', sa.String(length=30), nullable=False, comment='变化后状态'),
    sa.Column('reason', sa.Text(), nullable=False, comment='状态变化原因'),
    sa.Column('actor_type', sa.String(length=40), nullable=False, comment='操作者类型'),
    sa.Column('actor_id', sa.String(length=36), nullable=True, comment='操作者内部ID'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='事件时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.ForeignKeyConstraint(['task_id'], ['operation_tasks.id'], name=op.f('fk_task_events_task_id_operation_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_events')),
    comment='任务状态变化历史'
    )
    op.create_index('ix_task_events_task_time', 'task_events', ['task_id', 'occurred_at'], unique=False)
    op.create_table('work_orders',
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='来源任务ID'),
    sa.Column('schedule_id', sa.String(length=36), nullable=True, comment='来源排期ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='剧目内部ID'),
    sa.Column('publish_slot_id', sa.String(length=36), nullable=True, comment='发布时间档位ID'),
    sa.Column('playlist_id', sa.String(length=36), nullable=True, comment='计划播放列表ID'),
    sa.Column('production_date', sa.Date(), nullable=False, comment='生产日期'),
    sa.Column('target_publish_date', sa.Date(), nullable=False, comment='目标发布日期'),
    sa.Column('community_count', sa.SmallInteger(), server_default='0', nullable=False, comment='Community生产数量'),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False, comment='工单状态'),
    sa.Column('attempt_count', sa.Integer(), server_default='1', nullable=False, comment='工单运行轮次'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='首次开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('queued','running','completed','failed','cancelled')", name=op.f('ck_work_orders_valid_status')),
    sa.CheckConstraint('attempt_count >= 1', name=op.f('ck_work_orders_attempt_count_positive')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_work_orders_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_work_orders_drama_id_dramas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['playlist_id'], ['channel_playlists.id'], name=op.f('fk_work_orders_playlist_id_channel_playlists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publish_slot_id'], ['channel_publish_slots.id'], name=op.f('fk_work_orders_publish_slot_id_channel_publish_slots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['channel_schedule_entries.id'], name=op.f('fk_work_orders_schedule_id_channel_schedule_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['operation_tasks.id'], name=op.f('fk_work_orders_task_id_operation_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('task_id', name='uq_work_orders_task_id'),
    comment='任务下发后生成的生产工单'
    )
    op.create_index('ix_work_orders_channel_status', 'work_orders', ['channel_id', 'status'], unique=False)
    op.create_index('ix_work_orders_production_date_status', 'work_orders', ['production_date', 'status'], unique=False)
    op.create_table('operation_packages',
    sa.Column('work_order_id', sa.String(length=36), nullable=False, comment='生产工单ID'),
    sa.Column('schedule_id', sa.String(length=36), nullable=True, comment='来源排期ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='频道内部ID'),
    sa.Column('drama_id', sa.String(length=36), nullable=False, comment='剧目内部ID'),
    sa.Column('channel_dna_version_id', sa.String(length=36), nullable=True, comment='生产时采用的频道DNA版本ID'),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False, comment='工单内运营包版本号'),
    sa.Column('status', sa.String(length=30), server_default='building', nullable=False, comment='运营包状态'),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True, comment='合并完成时间'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='最终审核通过时间'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='交付时间'),
    sa.Column('review_note', sa.Text(), nullable=True, comment='最终审核意见'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('building','search_ready','title_ready','cover_ready','text_ready','community_ready','merge_ready','review_pending','changes_requested','approved','delivered','failed','archived')", name=op.f('ck_operation_packages_valid_status')),
    sa.ForeignKeyConstraint(['channel_dna_version_id'], ['channel_dna_versions.id'], name=op.f('fk_operation_packages_channel_dna_version_id_channel_dna_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_operation_packages_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drama_id'], ['dramas.id'], name=op.f('fk_operation_packages_drama_id_dramas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['channel_schedule_entries.id'], name=op.f('fk_operation_packages_schedule_id_channel_schedule_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_operation_packages_work_order_id_work_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_packages')),
    sa.UniqueConstraint('work_order_id', 'version_number', name='uq_operation_packages_version'),
    comment='某剧目、频道和工单的一版运营包'
    )
    op.create_index('ix_operation_packages_channel_status', 'operation_packages', ['channel_id', 'status'], unique=False)
    op.create_index('ix_operation_packages_work_order_status', 'operation_packages', ['work_order_id', 'status'], unique=False)
    op.create_table('package_artifacts',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('artifact_format', sa.String(length=10), nullable=False, comment='导出文件格式'),
    sa.Column('generation_number', sa.Integer(), nullable=False, comment='导出版本号'),
    sa.Column('storage_provider', sa.String(length=40), nullable=False, comment='存储提供方'),
    sa.Column('storage_key', sa.String(length=600), nullable=False, comment='存储对象键'),
    sa.Column('sha256', sa.String(length=64), nullable=True, comment='导出文件SHA-256摘要'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='导出状态'),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True, comment='导出完成时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='脱敏错误信息'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("artifact_format IN ('md','json')", name=op.f('ck_package_artifacts_valid_artifact_format')),
    sa.CheckConstraint("status IN ('pending','ready','failed','superseded')", name=op.f('ck_package_artifacts_valid_status')),
    sa.CheckConstraint('generation_number >= 1', name=op.f('ck_package_artifacts_generation_positive')),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_artifacts_package_id_operation_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_artifacts')),
    sa.UniqueConstraint('package_id', 'artifact_format', 'generation_number', name='uq_package_artifacts_version'),
    comment='由数据库内容派生的MD或JSON运营包文件'
    )
    op.create_table('package_community_posts',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('sequence_number', sa.SmallInteger(), nullable=False, comment='Community序号'),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False, comment='文案版本号'),
    sa.Column('language', sa.String(length=20), nullable=False, comment='文案语言'),
    sa.Column('localized_text', sa.Text(), nullable=False, comment='频道语言Community文案'),
    sa.Column('chinese_translation', sa.Text(), nullable=True, comment='Community文案中文翻译'),
    sa.Column('planned_time', sa.DateTime(timezone=True), nullable=True, comment='计划发布时间'),
    sa.Column('image_prompt', sa.Text(), nullable=True, comment='Community配图提示词'),
    sa.Column('selected', sa.Boolean(), server_default='0', nullable=False, comment='是否最终采用'),
    sa.Column('status', sa.String(length=20), server_default='generated', nullable=False, comment='Community文案状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('generated','selected','rejected','superseded','published')", name=op.f('ck_package_community_posts_valid_status')),
    sa.CheckConstraint('sequence_number >= 1 AND version_number >= 1', name=op.f('ck_package_community_posts_version_positive')),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_community_posts_package_id_operation_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_community_posts')),
    sa.UniqueConstraint('package_id', 'sequence_number', 'version_number', name='uq_package_community_posts_version'),
    comment='运营包Community文案版本'
    )
    op.create_index('ix_package_community_posts_package_status', 'package_community_posts', ['package_id', 'status', 'sequence_number'], unique=False)
    op.create_table('package_creative_slots',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('character_focus', sa.Text(), nullable=True, comment='人物焦点'),
    sa.Column('plot_focus', sa.Text(), nullable=True, comment='剧情焦点'),
    sa.Column('emotion', sa.Text(), nullable=True, comment='情绪方向'),
    sa.Column('title_hook', sa.Text(), nullable=True, comment='标题钩子'),
    sa.Column('thumbnail_scene', sa.Text(), nullable=True, comment='封面场景'),
    sa.Column('thumbnail_action', sa.Text(), nullable=True, comment='封面动作'),
    sa.Column('thumbnail_layout', sa.Text(), nullable=True, comment='封面构图'),
    sa.Column('description_angle', sa.Text(), nullable=True, comment='说明角度'),
    sa.Column('community_angle', sa.Text(), nullable=True, comment='Community角度'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_creative_slots_package_id_operation_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_creative_slots')),
    sa.UniqueConstraint('package_id', name='uq_package_creative_slots_package_id'),
    comment='运营包各创意维度的统一定位'
    )
    op.create_table('package_descriptions',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='说明版本号'),
    sa.Column('language', sa.String(length=20), nullable=False, comment='说明语言'),
    sa.Column('localized_text', sa.Text(), nullable=False, comment='频道语言说明正文'),
    sa.Column('chinese_translation', sa.Text(), nullable=True, comment='说明中文翻译'),
    sa.Column('pinned_comment', sa.Text(), nullable=True, comment='本版本置顶评论'),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True, comment='说明评分'),
    sa.Column('selected', sa.Boolean(), server_default='0', nullable=False, comment='是否最终采用'),
    sa.Column('status', sa.String(length=20), server_default='generated', nullable=False, comment='说明状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('generated','selected','rejected','superseded')", name=op.f('ck_package_descriptions_valid_status')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_package_descriptions_version_positive')),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_descriptions_package_id_operation_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_descriptions')),
    sa.UniqueConstraint('package_id', 'version_number', name='uq_package_descriptions_version'),
    comment='运营包说明及其重生版本'
    )
    op.create_table('package_playlist_assignments',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('playlist_id', sa.String(length=36), nullable=False, comment='播放列表ID'),
    sa.Column('rank_number', sa.Integer(), nullable=False, comment='候选排序'),
    sa.Column('rationale', sa.Text(), nullable=True, comment='推荐理由'),
    sa.Column('status', sa.String(length=20), server_default='candidate', nullable=False, comment='选择状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('candidate','selected','rejected')", name=op.f('ck_package_playlist_assignments_valid_status')),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_playlist_assignments_package_id_operation_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['channel_playlists.id'], name=op.f('fk_package_playlist_assignments_playlist_id_channel_playlists'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_playlist_assignments')),
    sa.UniqueConstraint('package_id', 'playlist_id', name='uq_package_playlist_assignments_pair'),
    comment='运营包播放列表候选与最终选择'
    )
    op.create_table('package_similarity_checks',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='当前运营包ID'),
    sa.Column('compared_package_id', sa.String(length=36), nullable=False, comment='对比运营包ID'),
    sa.Column('title_similarity', sa.Numeric(precision=6, scale=5), nullable=True, comment='标题相似度，0到1'),
    sa.Column('cover_similarity', sa.Numeric(precision=6, scale=5), nullable=True, comment='封面相似度，0到1'),
    sa.Column('description_similarity', sa.Numeric(precision=6, scale=5), nullable=True, comment='说明相似度，0到1'),
    sa.Column('creative_similarity', sa.Numeric(precision=6, scale=5), nullable=True, comment='整体创意相似度，0到1'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='检测结果'),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False, comment='检测时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("result IN ('pass','warning','fail')", name=op.f('ck_package_similarity_checks_valid_result')),
    sa.ForeignKeyConstraint(['compared_package_id'], ['operation_packages.id'], name=op.f('fk_package_similarity_checks_compared_package_id_operation_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_similarity_checks_package_id_operation_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_similarity_checks')),
    sa.UniqueConstraint('package_id', 'compared_package_id', name='uq_package_similarity_checks_pair'),
    comment='运营包与历史运营包的相似度检测'
    )
    op.create_index('ix_package_similarity_checks_package_result', 'package_similarity_checks', ['package_id', 'result'], unique=False)
    op.create_table('package_titles',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('variant_number', sa.SmallInteger(), nullable=False, comment='A/B候选编号'),
    sa.Column('generation_number', sa.Integer(), server_default='1', nullable=False, comment='该候选生成版本'),
    sa.Column('localized_title', sa.String(length=500), nullable=False, comment='频道语言标题'),
    sa.Column('chinese_translation', sa.String(length=1000), nullable=True, comment='标题中文翻译'),
    sa.Column('core_phrase', sa.String(length=255), nullable=True, comment='标题核心词'),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True, comment='标题评分'),
    sa.Column('selected', sa.Boolean(), server_default='0', nullable=False, comment='是否最终采用'),
    sa.Column('status', sa.String(length=20), server_default='generated', nullable=False, comment='标题状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('generated','selected','rejected','superseded')", name=op.f('ck_package_titles_valid_status')),
    sa.CheckConstraint('variant_number >= 1 AND generation_number >= 1', name=op.f('ck_package_titles_version_positive')),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_titles_package_id_operation_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_titles')),
    sa.UniqueConstraint('package_id', 'variant_number', 'generation_number', name='uq_package_titles_version'),
    comment='运营包标题候选及重生版本'
    )
    op.create_index('ix_package_titles_package_status', 'package_titles', ['package_id', 'status', 'variant_number'], unique=False)
    op.create_table('package_validation_results',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('validator_code', sa.String(length=100), nullable=False, comment='检测器代码'),
    sa.Column('node_type', sa.String(length=20), nullable=True, comment='关联生产节点'),
    sa.Column('field_reference', sa.String(length=255), nullable=True, comment='关联字段定位'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='检测结果'),
    sa.Column('message', sa.Text(), nullable=False, comment='检测说明'),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False, comment='检测时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("result IN ('pass','warning','fail')", name=op.f('ck_package_validation_results_valid_result')),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_validation_results_package_id_operation_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_validation_results')),
    comment='运营包各项自动检测结果'
    )
    op.create_index('ix_package_validation_results_package_result', 'package_validation_results', ['package_id', 'result', 'validator_code'], unique=False)
    op.create_table('production_node_runs',
    sa.Column('work_order_id', sa.String(length=36), nullable=False, comment='生产工单ID'),
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('node_type', sa.String(length=20), nullable=False, comment='生产节点类型'),
    sa.Column('sequence_number', sa.SmallInteger(), nullable=False, comment='节点顺序'),
    sa.Column('attempt_number', sa.Integer(), nullable=False, comment='该节点尝试次数'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='节点运行状态'),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False, comment='节点运行幂等键'),
    sa.Column('worker_key', sa.String(length=120), nullable=True, comment='领取该节点的工作器标识'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('error_code', sa.String(length=120), nullable=True, comment='错误代码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='脱敏错误信息'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("node_type IN ('search','title','cover','description','community','merge')", name=op.f('ck_production_node_runs_valid_node_type')),
    sa.CheckConstraint("status IN ('pending','queued','running','completed','failed','skipped','cancelled')", name=op.f('ck_production_node_runs_valid_status')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_production_node_runs_attempt_positive')),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_production_node_runs_package_id_operation_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_production_node_runs_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_node_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_production_node_runs_idempotency_key'),
    sa.UniqueConstraint('work_order_id', 'node_type', 'attempt_number', name='uq_production_node_runs_attempt'),
    comment='生产工单各节点的每次运行尝试'
    )
    op.create_index('ix_production_node_runs_work_order_status', 'production_node_runs', ['work_order_id', 'status', 'node_type'], unique=False)
    op.create_table('community_post_assets',
    sa.Column('community_post_id', sa.String(length=36), nullable=False, comment='Community帖子ID'),
    sa.Column('asset_id', sa.String(length=36), nullable=False, comment='媒体资产ID'),
    sa.Column('position_number', sa.SmallInteger(), nullable=False, comment='图片顺序'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint('position_number >= 1', name=op.f('ck_community_post_assets_position_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], name=op.f('fk_community_post_assets_asset_id_media_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['community_post_id'], ['package_community_posts.id'], name=op.f('fk_community_post_assets_community_post_id_package_community_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_post_assets')),
    sa.UniqueConstraint('community_post_id', 'asset_id', name='uq_community_post_assets_asset'),
    sa.UniqueConstraint('community_post_id', 'position_number', name='uq_community_post_assets_position'),
    comment='Community帖子与一张或多张图片的关联'
    )
    op.create_table('package_cover_variants',
    sa.Column('package_id', sa.String(length=36), nullable=False, comment='运营包ID'),
    sa.Column('title_id', sa.String(length=36), nullable=False, comment='对应标题候选ID'),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False, comment='封面比例'),
    sa.Column('generation_number', sa.Integer(), server_default='1', nullable=False, comment='该比例生成版本'),
    sa.Column('creative_prompt', sa.Text(), nullable=False, comment='封面生成提示词'),
    sa.Column('asset_id', sa.String(length=36), nullable=True, comment='生成后的图片资产ID'),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True, comment='封面评分'),
    sa.Column('selected', sa.Boolean(), server_default='0', nullable=False, comment='是否最终采用'),
    sa.Column('status', sa.String(length=20), server_default='prompt_ready', nullable=False, comment='封面状态'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("aspect_ratio IN ('4:5','16:9')", name=op.f('ck_package_cover_variants_valid_aspect_ratio')),
    sa.CheckConstraint("status IN ('prompt_ready','rendered','selected','rejected','superseded')", name=op.f('ck_package_cover_variants_valid_status')),
    sa.CheckConstraint('generation_number >= 1', name=op.f('ck_package_cover_variants_generation_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], name=op.f('fk_package_cover_variants_asset_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['operation_packages.id'], name=op.f('fk_package_cover_variants_package_id_operation_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['package_titles.id'], name=op.f('fk_package_cover_variants_title_id_package_titles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_cover_variants')),
    sa.UniqueConstraint('package_id', 'title_id', 'aspect_ratio', 'generation_number', name='uq_package_cover_variants_version'),
    comment='与标题候选一一对应的4:5和16:9封面版本'
    )
    op.create_index('ix_package_cover_variants_package_status', 'package_cover_variants', ['package_id', 'status', 'aspect_ratio'], unique=False)
    op.add_column('media_assets', sa.Column('operation_package_id', sa.String(length=36), nullable=True, comment='所属运营包ID'))
    op.create_foreign_key(op.f('fk_media_assets_operation_package_id_operation_packages'), 'media_assets', 'operation_packages', ['operation_package_id'], ['id'], ondelete='SET NULL')
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_media_assets_operation_package_id_operation_packages'), 'media_assets', type_='foreignkey')
    op.drop_column('media_assets', 'operation_package_id')
    op.drop_index('ix_package_cover_variants_package_status', table_name='package_cover_variants')
    op.drop_table('package_cover_variants')
    op.drop_table('community_post_assets')
    op.drop_index('ix_production_node_runs_work_order_status', table_name='production_node_runs')
    op.drop_table('production_node_runs')
    op.drop_index('ix_package_validation_results_package_result', table_name='package_validation_results')
    op.drop_table('package_validation_results')
    op.drop_index('ix_package_titles_package_status', table_name='package_titles')
    op.drop_table('package_titles')
    op.drop_index('ix_package_similarity_checks_package_result', table_name='package_similarity_checks')
    op.drop_table('package_similarity_checks')
    op.drop_table('package_playlist_assignments')
    op.drop_table('package_descriptions')
    op.drop_table('package_creative_slots')
    op.drop_index('ix_package_community_posts_package_status', table_name='package_community_posts')
    op.drop_table('package_community_posts')
    op.drop_table('package_artifacts')
    op.drop_index('ix_operation_packages_work_order_status', table_name='operation_packages')
    op.drop_index('ix_operation_packages_channel_status', table_name='operation_packages')
    op.drop_table('operation_packages')
    op.drop_index('ix_work_orders_production_date_status', table_name='work_orders')
    op.drop_index('ix_work_orders_channel_status', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index('ix_task_events_task_time', table_name='task_events')
    op.drop_table('task_events')
    op.drop_index('ix_operation_tasks_date_status', table_name='operation_tasks')
    op.drop_index('ix_operation_tasks_channel_status', table_name='operation_tasks')
    op.drop_table('operation_tasks')
    op.drop_index('ix_system_events_entity_time', table_name='system_events')
    op.drop_table('system_events')
    # ### end Alembic commands ###
