"""add channel pinned comment template versions

Revision ID: caf2e52fad7e
Revises: 467e92fbfc75
Create Date: 2026-08-16 19:39:43.923214
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'caf2e52fad7e'
down_revision: Union[str, None] = '467e92fbfc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_pinned_comment_templates',
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='所属频道内部ID'),
    sa.Column('language', sa.String(length=20), nullable=False, comment='模板语言'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='频道语言内版本号'),
    sa.Column('body', sa.Text(), nullable=False, comment='置顶评论正文'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='模板状态'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='结束生效时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='系统内部稳定主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.CheckConstraint("status IN ('draft','active','superseded','archived')", name=op.f('ck_channel_pinned_comment_templates_valid_status')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_channel_pinned_comment_templates_version_positive')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_pinned_comment_templates_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_pinned_comment_templates')),
    sa.UniqueConstraint('channel_id', 'language', 'version_number', name='uq_channel_pinned_comment_templates_version'),
    comment='频道默认置顶评论模板版本'
    )
    op.create_index('ix_channel_pinned_comment_templates_channel_language_status', 'channel_pinned_comment_templates', ['channel_id', 'language', 'status'], unique=False)
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_channel_pinned_comment_templates_channel_language_status', table_name='channel_pinned_comment_templates')
    op.drop_table('channel_pinned_comment_templates')
    # ### end Alembic commands ###
