"""enforce community publishing slot rules

Revision ID: cbe100b9853c
Revises: caf2e52fad7e
Create Date: 2026-08-16 19:58:43.545594
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbe100b9853c'
down_revision: Union[str, None] = 'caf2e52fad7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('ck_channel_community_slots_mode_fields_present'),
        'channel_community_slots',
        type_='check',
    )
    op.create_check_constraint(
        op.f('ck_channel_community_slots_mode_fields_present'),
        'channel_community_slots',
        "(schedule_mode = 'relative' AND publish_slot_id IS NOT NULL AND local_time IS NULL) OR "
        "(schedule_mode = 'fixed' AND publish_slot_id IS NULL AND local_time IS NOT NULL AND offset_minutes = 0)",
    )
    op.create_unique_constraint('uq_channel_community_slots_fixed_rule', 'channel_community_slots', ['channel_id', 'local_time', 'timezone'])
    op.create_unique_constraint('uq_channel_community_slots_relative_rule', 'channel_community_slots', ['channel_id', 'publish_slot_id', 'offset_minutes'])
    op.execute(sa.text("""
        REPLACE INTO schema_comments (table_name, column_name, chinese_comment, updated_at)
        SELECT table_name, column_name, column_comment, UTC_TIMESTAMP()
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND column_comment <> ''
        UNION ALL
        SELECT table_name, '__table__', table_comment, UTC_TIMESTAMP()
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_comment <> ''
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_channel_community_slots_relative_rule', 'channel_community_slots', type_='unique')
    op.drop_constraint('uq_channel_community_slots_fixed_rule', 'channel_community_slots', type_='unique')
    op.drop_constraint(
        op.f('ck_channel_community_slots_mode_fields_present'),
        'channel_community_slots',
        type_='check',
    )
    op.create_check_constraint(
        op.f('ck_channel_community_slots_mode_fields_present'),
        'channel_community_slots',
        "(schedule_mode = 'relative' AND publish_slot_id IS NOT NULL) OR "
        "(schedule_mode = 'fixed' AND local_time IS NOT NULL)",
    )
    # ### end Alembic commands ###
